//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 10:55:05 AM CST 
//


package org.atdl4j.fixatdl.core;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.atdl4j.fixatdl.validation.EditT;


/**
 *  This element is used as a container for strategy elements. The motivation behind this element is to allow an algorithm provider to describe more than one algorithm in a single XML document.     
 * 
 * <p>Java class for Strategies_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Strategies_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.fixprotocol.org/FIXatdl-1-1/Core}Description" minOccurs="0"/>
 *         &lt;element ref="{http://www.fixprotocol.org/FIXatdl-1-1/Validation}Edit" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Strategy" type="{http://www.fixprotocol.org/FIXatdl-1-1/Core}Strategy_t" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="strategyIdentifierTag" use="required" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="versionIdentifierTag" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="draftFlagIdentifierTag" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="changeStrategyOnCxlRpl" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="imageLocation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="tag957Support" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Strategies_t", propOrder = {
    "description",
    "edit",
    "strategy"
})
public class StrategiesT {

    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Edit", namespace = "http://www.fixprotocol.org/FIXatdl-1-1/Validation")
    protected List<EditT> edit;
    @XmlElement(name = "Strategy", required = true)
    protected List<StrategyT> strategy;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger strategyIdentifierTag;
    @XmlAttribute
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger versionIdentifierTag;
    @XmlAttribute
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger draftFlagIdentifierTag;
    @XmlAttribute
    protected Boolean changeStrategyOnCxlRpl;
    @XmlAttribute
    protected String imageLocation;
    @XmlAttribute
    protected Boolean tag957Support;

    /**
     * Description of the set of strategies or a description of the firm providing them.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Global rule definition. When used in this capacity Edit.id is a required attribute. Individual strategies may incorporate these rules by a reference to their 'id' attributes.Gets the value of the edit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the edit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEdit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EditT }
     * 
     * 
     */
    public List<EditT> getEdit() {
        if (edit == null) {
            edit = new ArrayList<EditT>();
        }
        return this.edit;
    }

    /**
     * Gets the value of the strategy property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the strategy property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStrategy().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StrategyT }
     * 
     * 
     */
    public List<StrategyT> getStrategy() {
        if (strategy == null) {
            strategy = new ArrayList<StrategyT>();
        }
        return this.strategy;
    }

    /**
     * Gets the value of the strategyIdentifierTag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getStrategyIdentifierTag() {
        return strategyIdentifierTag;
    }

    /**
     * Sets the value of the strategyIdentifierTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setStrategyIdentifierTag(BigInteger value) {
        this.strategyIdentifierTag = value;
    }

    /**
     * Gets the value of the versionIdentifierTag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getVersionIdentifierTag() {
        return versionIdentifierTag;
    }

    /**
     * Sets the value of the versionIdentifierTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setVersionIdentifierTag(BigInteger value) {
        this.versionIdentifierTag = value;
    }

    /**
     * Gets the value of the draftFlagIdentifierTag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getDraftFlagIdentifierTag() {
        return draftFlagIdentifierTag;
    }

    /**
     * Sets the value of the draftFlagIdentifierTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setDraftFlagIdentifierTag(BigInteger value) {
        this.draftFlagIdentifierTag = value;
    }

    /**
     * Gets the value of the changeStrategyOnCxlRpl property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isChangeStrategyOnCxlRpl() {
        return changeStrategyOnCxlRpl;
    }

    /**
     * Sets the value of the changeStrategyOnCxlRpl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setChangeStrategyOnCxlRpl(Boolean value) {
        this.changeStrategyOnCxlRpl = value;
    }

    /**
     * Gets the value of the imageLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageLocation() {
        return imageLocation;
    }

    /**
     * Sets the value of the imageLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageLocation(String value) {
        this.imageLocation = value;
    }

    /**
     * Gets the value of the tag957Support property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isTag957Support() {
        if (tag957Support == null) {
            return false;
        } else {
            return tag957Support;
        }
    }

    /**
     * Sets the value of the tag957Support property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTag957Support(Boolean value) {
        this.tag957Support = value;
    }

}
