//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 10:55:05 AM CST 
//


package org.atdl4j.fixatdl.validation;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Specifies a strategy-wide rule consisting of a boolean expression and an error message to be didsplayed when the boolean expression evaluates to False().
 * 
 * <p>Java class for StrategyEdit_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StrategyEdit_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.fixprotocol.org/FIXatdl-1-1/Core}Description" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;element name="Edit" type="{http://www.fixprotocol.org/FIXatdl-1-1/Validation}Edit_t"/>
 *           &lt;element name="EditRef" type="{http://www.fixprotocol.org/FIXatdl-1-1/Validation}EditRef_t"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *       &lt;attribute name="errorMessage" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StrategyEdit_t", propOrder = {
    "description",
    "edit",
    "editRef"
})
public class StrategyEditT {

    @XmlElement(name = "Description", namespace = "http://www.fixprotocol.org/FIXatdl-1-1/Core")
    protected String description;
    @XmlElement(name = "Edit")
    protected EditT edit;
    @XmlElement(name = "EditRef")
    protected EditRefT editRef;
    @XmlAttribute(required = true)
    protected String errorMessage;

    /**
     * Optional description of the Strategy Edit.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the edit property.
     * 
     * @return
     *     possible object is
     *     {@link EditT }
     *     
     */
    public EditT getEdit() {
        return edit;
    }

    /**
     * Sets the value of the edit property.
     * 
     * @param value
     *     allowed object is
     *     {@link EditT }
     *     
     */
    public void setEdit(EditT value) {
        this.edit = value;
    }

    /**
     * Gets the value of the editRef property.
     * 
     * @return
     *     possible object is
     *     {@link EditRefT }
     *     
     */
    public EditRefT getEditRef() {
        return editRef;
    }

    /**
     * Sets the value of the editRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link EditRefT }
     *     
     */
    public void setEditRef(EditRefT value) {
        this.editRef = value;
    }

    /**
     * Gets the value of the errorMessage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getErrorMessage() {
        return errorMessage;
    }

    /**
     * Sets the value of the errorMessage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setErrorMessage(String value) {
        this.errorMessage = value;
    }

}
