//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 02:37:55 AM JST 
//


package org.atdl4j.atdl.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for LocalMktTime_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocalMktTime_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fixprotocol.org/ATDL-1-1/Core}Parameter_t">
 *       &lt;attribute name="minValue" type="{http://www.fixprotocol.org/ATDL-1-1/Core}LocalMktTime" />
 *       &lt;attribute name="maxValue" type="{http://www.fixprotocol.org/ATDL-1-1/Core}LocalMktTime" />
 *       &lt;attribute name="localMktTz" use="required" type="{http://www.fixprotocol.org/ATDL-1-1/Timezones}LocalMktTz_t" />
 *       &lt;attribute name="constValue" type="{http://www.fixprotocol.org/ATDL-1-1/Core}LocalMktTime" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocalMktTime_t")
public class LocalMktTimeT
    extends ParameterT
{

    @XmlAttribute
    protected XMLGregorianCalendar minValue;
    @XmlAttribute
    protected XMLGregorianCalendar maxValue;
    @XmlAttribute(required = true)
    protected String localMktTz;
    @XmlAttribute
    protected XMLGregorianCalendar constValue;

    /**
     * Gets the value of the minValue property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMinValue() {
        return minValue;
    }

    /**
     * Sets the value of the minValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMinValue(XMLGregorianCalendar value) {
        this.minValue = value;
    }

    /**
     * Gets the value of the maxValue property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMaxValue() {
        return maxValue;
    }

    /**
     * Sets the value of the maxValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMaxValue(XMLGregorianCalendar value) {
        this.maxValue = value;
    }

    /**
     * Gets the value of the localMktTz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLocalMktTz() {
        return localMktTz;
    }

    /**
     * Sets the value of the localMktTz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLocalMktTz(String value) {
        this.localMktTz = value;
    }

    /**
     * Gets the value of the constValue property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getConstValue() {
        return constValue;
    }

    /**
     * Sets the value of the constValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setConstValue(XMLGregorianCalendar value) {
        this.constValue = value;
    }

}
