//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.30 at 11:18:20 PM JST 
//


package org.atdl4j.atdl.core;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.atdl4j.atdl.core package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Strategies_QNAME = new QName("http://www.fixprotocol.org/ATDL-1-1/Core", "Strategies");
    private final static QName _Description_QNAME = new QName("http://www.fixprotocol.org/ATDL-1-1/Core", "Description");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.atdl4j.atdl.core
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link QtyT }
     * 
     */
    public QtyT createQtyT() {
        return new QtyT();
    }

    /**
     * Create an instance of {@link CurrencyT }
     * 
     */
    public CurrencyT createCurrencyT() {
        return new CurrencyT();
    }

    /**
     * Create an instance of {@link BooleanT }
     * 
     */
    public BooleanT createBooleanT() {
        return new BooleanT();
    }

    /**
     * Create an instance of {@link SeqNumT }
     * 
     */
    public SeqNumT createSeqNumT() {
        return new SeqNumT();
    }

    /**
     * Create an instance of {@link DataT }
     * 
     */
    public DataT createDataT() {
        return new DataT();
    }

    /**
     * Create an instance of {@link SecurityTypesT.SecurityType }
     * 
     */
    public SecurityTypesT.SecurityType createSecurityTypesTSecurityType() {
        return new SecurityTypesT.SecurityType();
    }

    /**
     * Create an instance of {@link TZTimestampT }
     * 
     */
    public TZTimestampT createTZTimestampT() {
        return new TZTimestampT();
    }

    /**
     * Create an instance of {@link RegionsT }
     * 
     */
    public RegionsT createRegionsT() {
        return new RegionsT();
    }

    /**
     * Create an instance of {@link EnumPairT }
     * 
     */
    public EnumPairT createEnumPairT() {
        return new EnumPairT();
    }

    /**
     * Create an instance of {@link AmtT }
     * 
     */
    public AmtT createAmtT() {
        return new AmtT();
    }

    /**
     * Create an instance of {@link LocalMktDateT }
     * 
     */
    public LocalMktDateT createLocalMktDateT() {
        return new LocalMktDateT();
    }

    /**
     * Create an instance of {@link MonthYearT }
     * 
     */
    public MonthYearT createMonthYearT() {
        return new MonthYearT();
    }

    /**
     * Create an instance of {@link PercentageT }
     * 
     */
    public PercentageT createPercentageT() {
        return new PercentageT();
    }

    /**
     * Create an instance of {@link TagNumT }
     * 
     */
    public TagNumT createTagNumT() {
        return new TagNumT();
    }

    /**
     * Create an instance of {@link SecurityTypesT }
     * 
     */
    public SecurityTypesT createSecurityTypesT() {
        return new SecurityTypesT();
    }

    /**
     * Create an instance of {@link StrategiesT }
     * 
     */
    public StrategiesT createStrategiesT() {
        return new StrategiesT();
    }

    /**
     * Create an instance of {@link StrategyT }
     * 
     */
    public StrategyT createStrategyT() {
        return new StrategyT();
    }

    /**
     * Create an instance of {@link NumInGroupT }
     * 
     */
    public NumInGroupT createNumInGroupT() {
        return new NumInGroupT();
    }

    /**
     * Create an instance of {@link StringT }
     * 
     */
    public StringT createStringT() {
        return new StringT();
    }

    /**
     * Create an instance of {@link UTCTimestampT }
     * 
     */
    public UTCTimestampT createUTCTimestampT() {
        return new UTCTimestampT();
    }

    /**
     * Create an instance of {@link LanguageT }
     * 
     */
    public LanguageT createLanguageT() {
        return new LanguageT();
    }

    /**
     * Create an instance of {@link TenorT }
     * 
     */
    public TenorT createTenorT() {
        return new TenorT();
    }

    /**
     * Create an instance of {@link LengthT }
     * 
     */
    public LengthT createLengthT() {
        return new LengthT();
    }

    /**
     * Create an instance of {@link PriceT }
     * 
     */
    public PriceT createPriceT() {
        return new PriceT();
    }

    /**
     * Create an instance of {@link ExchangeT }
     * 
     */
    public ExchangeT createExchangeT() {
        return new ExchangeT();
    }

    /**
     * Create an instance of {@link MultipleCharValueT }
     * 
     */
    public MultipleCharValueT createMultipleCharValueT() {
        return new MultipleCharValueT();
    }

    /**
     * Create an instance of {@link FloatT }
     * 
     */
    public FloatT createFloatT() {
        return new FloatT();
    }

    /**
     * Create an instance of {@link MultipleStringValueT }
     * 
     */
    public MultipleStringValueT createMultipleStringValueT() {
        return new MultipleStringValueT();
    }

    /**
     * Create an instance of {@link CountryT }
     * 
     */
    public CountryT createCountryT() {
        return new CountryT();
    }

    /**
     * Create an instance of {@link PriceOffsetT }
     * 
     */
    public PriceOffsetT createPriceOffsetT() {
        return new PriceOffsetT();
    }

    /**
     * Create an instance of {@link CharT }
     * 
     */
    public CharT createCharT() {
        return new CharT();
    }

    /**
     * Create an instance of {@link NumericT }
     * 
     */
    public NumericT createNumericT() {
        return new NumericT();
    }

    /**
     * Create an instance of {@link RegionT }
     * 
     */
    public RegionT createRegionT() {
        return new RegionT();
    }

    /**
     * Create an instance of {@link UTCDateOnlyT }
     * 
     */
    public UTCDateOnlyT createUTCDateOnlyT() {
        return new UTCDateOnlyT();
    }

    /**
     * Create an instance of {@link MarketT }
     * 
     */
    public MarketT createMarketT() {
        return new MarketT();
    }

    /**
     * Create an instance of {@link TZTimeOnlyT }
     * 
     */
    public TZTimeOnlyT createTZTimeOnlyT() {
        return new TZTimeOnlyT();
    }

    /**
     * Create an instance of {@link IntT }
     * 
     */
    public IntT createIntT() {
        return new IntT();
    }

    /**
     * Create an instance of {@link RepeatingGroupT }
     * 
     */
    public RepeatingGroupT createRepeatingGroupT() {
        return new RepeatingGroupT();
    }

    /**
     * Create an instance of {@link MarketsT }
     * 
     */
    public MarketsT createMarketsT() {
        return new MarketsT();
    }

    /**
     * Create an instance of {@link UTCTimeOnlyT }
     * 
     */
    public UTCTimeOnlyT createUTCTimeOnlyT() {
        return new UTCTimeOnlyT();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StrategiesT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/ATDL-1-1/Core", name = "Strategies")
    public JAXBElement<StrategiesT> createStrategies(StrategiesT value) {
        return new JAXBElement<StrategiesT>(_Strategies_QNAME, StrategiesT.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/ATDL-1-1/Core", name = "Description")
    public JAXBElement<String> createDescription(String value) {
        return new JAXBElement<String>(_Description_QNAME, String.class, null, value);
    }

}
