//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 02:37:55 AM JST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.fixprotocol.org/ATDL-1-1/Core", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.atdl4j.atdl.core;
