//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.30 at 11:18:20 PM JST 
//


package org.atdl4j.atdl.core;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Parameter_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Parameter_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.fixprotocol.org/ATDL-1-1/Core}Description" minOccurs="0"/>
 *         &lt;element name="EnumPair" type="{http://www.fixprotocol.org/ATDL-1-1/Core}EnumPair_t" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[A-Za-z][A-za-z0-9_]{0,255}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="fixTag" type="{http://www.w3.org/2001/XMLSchema}positiveInteger" />
 *       &lt;attribute name="const" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="use" type="{http://www.fixprotocol.org/ATDL-1-1/Core}Use_t" default="optional" />
 *       &lt;attribute name="mutableOnCxlRpl" type="{http://www.w3.org/2001/XMLSchema}boolean" default="true" />
 *       &lt;attribute name="revertOnCxlRpl" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *       &lt;attribute name="definedByFIX" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Parameter_t", propOrder = {
    "description",
    "enumPair"
})
@XmlSeeAlso({
    LanguageT.class,
    LengthT.class,
    DataT.class,
    StringT.class,
    ExchangeT.class,
    CharT.class,
    CurrencyT.class,
    UTCTimeOnlyT.class,
    SeqNumT.class,
    TagNumT.class,
    TZTimestampT.class,
    LocalMktDateT.class,
    IntT.class,
    MultipleStringValueT.class,
    MonthYearT.class,
    TenorT.class,
    BooleanT.class,
    TZTimeOnlyT.class,
    UTCDateOnlyT.class,
    MultipleCharValueT.class,
    NumericT.class,
    UTCTimestampT.class,
    NumInGroupT.class
})
public abstract class ParameterT {

    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "EnumPair")
    protected List<EnumPairT> enumPair;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute
    @XmlSchemaType(name = "positiveInteger")
    protected BigInteger fixTag;
    @XmlAttribute(name = "const")
    protected Boolean _const;
    @XmlAttribute
    protected UseT use;
    @XmlAttribute
    protected Boolean mutableOnCxlRpl;
    @XmlAttribute
    protected Boolean revertOnCxlRpl;
    @XmlAttribute
    protected Boolean definedByFIX;

    /**
     * Description of the Parameter.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the enumPair property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the enumPair property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEnumPair().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EnumPairT }
     * 
     * 
     */
    public List<EnumPairT> getEnumPair() {
        if (enumPair == null) {
            enumPair = new ArrayList<EnumPairT>();
        }
        return this.enumPair;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the fixTag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getFixTag() {
        return fixTag;
    }

    /**
     * Sets the value of the fixTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setFixTag(BigInteger value) {
        this.fixTag = value;
    }

    /**
     * Gets the value of the const property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isConst() {
        if (_const == null) {
            return false;
        } else {
            return _const;
        }
    }

    /**
     * Sets the value of the const property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setConst(Boolean value) {
        this._const = value;
    }

    /**
     * Gets the value of the use property.
     * 
     * @return
     *     possible object is
     *     {@link UseT }
     *     
     */
    public UseT getUse() {
        if (use == null) {
            return UseT.OPTIONAL;
        } else {
            return use;
        }
    }

    /**
     * Sets the value of the use property.
     * 
     * @param value
     *     allowed object is
     *     {@link UseT }
     *     
     */
    public void setUse(UseT value) {
        this.use = value;
    }

    /**
     * Gets the value of the mutableOnCxlRpl property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isMutableOnCxlRpl() {
        if (mutableOnCxlRpl == null) {
            return true;
        } else {
            return mutableOnCxlRpl;
        }
    }

    /**
     * Sets the value of the mutableOnCxlRpl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMutableOnCxlRpl(Boolean value) {
        this.mutableOnCxlRpl = value;
    }

    /**
     * Gets the value of the revertOnCxlRpl property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isRevertOnCxlRpl() {
        return revertOnCxlRpl;
    }

    /**
     * Sets the value of the revertOnCxlRpl property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setRevertOnCxlRpl(Boolean value) {
        this.revertOnCxlRpl = value;
    }

    /**
     * Gets the value of the definedByFIX property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isDefinedByFIX() {
        if (definedByFIX == null) {
            return false;
        } else {
            return definedByFIX;
        }
    }

    /**
     * Sets the value of the definedByFIX property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setDefinedByFIX(Boolean value) {
        this.definedByFIX = value;
    }

}
