//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 02:37:55 AM JST 
//


package org.atdl4j.atdl.core;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *         The list of security types (by CFI Code) that the given strategy is valid for.  The absence of any
 *         security types implies that the strategy is valid for all markets.
 *       
 * 
 * <p>Java class for SecurityTypes_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SecurityTypes_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="SecurityType">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;attribute name="name" use="required">
 *                   &lt;simpleType>
 *                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                       &lt;enumeration value="E"/>
 *                       &lt;enumeration value="D"/>
 *                       &lt;enumeration value="O"/>
 *                       &lt;enumeration value="F"/>
 *                       &lt;enumeration value="M"/>
 *                     &lt;/restriction>
 *                   &lt;/simpleType>
 *                 &lt;/attribute>
 *                 &lt;attribute name="inclusion" use="required" type="{http://www.fixprotocol.org/ATDL-1-1/Core}Inclusion_t" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SecurityTypes_t", propOrder = {
    "securityType"
})
public class SecurityTypesT {

    @XmlElement(name = "SecurityType", required = true)
    protected List<SecurityTypesT.SecurityType> securityType;

    /**
     * Gets the value of the securityType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the securityType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSecurityType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SecurityTypesT.SecurityType }
     * 
     * 
     */
    public List<SecurityTypesT.SecurityType> getSecurityType() {
        if (securityType == null) {
            securityType = new ArrayList<SecurityTypesT.SecurityType>();
        }
        return this.securityType;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;attribute name="name" use="required">
     *         &lt;simpleType>
     *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *             &lt;enumeration value="E"/>
     *             &lt;enumeration value="D"/>
     *             &lt;enumeration value="O"/>
     *             &lt;enumeration value="F"/>
     *             &lt;enumeration value="M"/>
     *           &lt;/restriction>
     *         &lt;/simpleType>
     *       &lt;/attribute>
     *       &lt;attribute name="inclusion" use="required" type="{http://www.fixprotocol.org/ATDL-1-1/Core}Inclusion_t" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "")
    public static class SecurityType {

        @XmlAttribute(required = true)
        protected String name;
        @XmlAttribute(required = true)
        protected InclusionT inclusion;

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the inclusion property.
         * 
         * @return
         *     possible object is
         *     {@link InclusionT }
         *     
         */
        public InclusionT getInclusion() {
            return inclusion;
        }

        /**
         * Sets the value of the inclusion property.
         * 
         * @param value
         *     allowed object is
         *     {@link InclusionT }
         *     
         */
        public void setInclusion(InclusionT value) {
            this.inclusion = value;
        }

    }

}
