//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.30 at 11:18:20 PM JST 
//


package org.atdl4j.atdl.core;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.atdl4j.atdl.layout.StrategyLayoutT;
import org.atdl4j.atdl.validation.EditT;
import org.atdl4j.atdl.validation.StrategyEditT;


/**
 * <p>Java class for Strategy_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Strategy_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.fixprotocol.org/ATDL-1-1/Core}Description" minOccurs="0"/>
 *         &lt;element name="Regions" type="{http://www.fixprotocol.org/ATDL-1-1/Core}Regions_t" minOccurs="0"/>
 *         &lt;element name="Markets" type="{http://www.fixprotocol.org/ATDL-1-1/Core}Markets_t" minOccurs="0"/>
 *         &lt;element name="SecurityTypes" type="{http://www.fixprotocol.org/ATDL-1-1/Core}SecurityTypes_t" minOccurs="0"/>
 *         &lt;element name="Parameter" type="{http://www.fixprotocol.org/ATDL-1-1/Core}Parameter_t" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.fixprotocol.org/ATDL-1-1/Validation}Edit" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{http://www.fixprotocol.org/ATDL-1-1/Layout}StrategyLayout" minOccurs="0"/>
 *         &lt;element name="RepeatingGroup" type="{http://www.fixprotocol.org/ATDL-1-1/Core}RepeatingGroup_t" minOccurs="0"/>
 *         &lt;element ref="{http://www.fixprotocol.org/ATDL-1-1/Validation}StrategyEdit" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;pattern value="[A-Za-z][A-za-z0-9_]{0,255}"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="uiRep" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="wireValue" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="fixMsgType" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="disclosureDoc" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="sentOrderLink" type="{http://www.w3.org/2001/XMLSchema}anyURI" />
 *       &lt;attribute name="providerID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="providerSubID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="imageLocation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="totalLegs" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="totalOrders" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="commonIDTag" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="totalOrdersTag" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *       &lt;attribute name="orderSequenceTag" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Strategy_t", propOrder = {
    "description",
    "regions",
    "markets",
    "securityTypes",
    "parameter",
    "edit",
    "strategyLayout",
    "repeatingGroup",
    "strategyEdit"
})
public class StrategyT {

    @XmlElement(name = "Description")
    protected String description;
    @XmlElement(name = "Regions")
    protected RegionsT regions;
    @XmlElement(name = "Markets")
    protected MarketsT markets;
    @XmlElement(name = "SecurityTypes")
    protected SecurityTypesT securityTypes;
    @XmlElement(name = "Parameter")
    protected List<ParameterT> parameter;
    @XmlElement(name = "Edit", namespace = "http://www.fixprotocol.org/ATDL-1-1/Validation")
    protected List<EditT> edit;
    @XmlElement(name = "StrategyLayout", namespace = "http://www.fixprotocol.org/ATDL-1-1/Layout")
    protected StrategyLayoutT strategyLayout;
    @XmlElement(name = "RepeatingGroup")
    protected RepeatingGroupT repeatingGroup;
    @XmlElement(name = "StrategyEdit", namespace = "http://www.fixprotocol.org/ATDL-1-1/Validation")
    protected List<StrategyEditT> strategyEdit;
    @XmlAttribute(required = true)
    protected String name;
    @XmlAttribute
    protected String uiRep;
    @XmlAttribute(required = true)
    protected String wireValue;
    @XmlAttribute(required = true)
    protected String version;
    @XmlAttribute
    protected String fixMsgType;
    @XmlAttribute
    @XmlSchemaType(name = "anyURI")
    protected String disclosureDoc;
    @XmlAttribute
    @XmlSchemaType(name = "anyURI")
    protected String sentOrderLink;
    @XmlAttribute
    protected String providerID;
    @XmlAttribute
    protected String providerSubID;
    @XmlAttribute
    protected String imageLocation;
    @XmlAttribute
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger totalLegs;
    @XmlAttribute
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger totalOrders;
    @XmlAttribute
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger commonIDTag;
    @XmlAttribute
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger totalOrdersTag;
    @XmlAttribute
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger orderSequenceTag;

    /**
     * Description of the Strategy.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the regions property.
     * 
     * @return
     *     possible object is
     *     {@link RegionsT }
     *     
     */
    public RegionsT getRegions() {
        return regions;
    }

    /**
     * Sets the value of the regions property.
     * 
     * @param value
     *     allowed object is
     *     {@link RegionsT }
     *     
     */
    public void setRegions(RegionsT value) {
        this.regions = value;
    }

    /**
     * Gets the value of the markets property.
     * 
     * @return
     *     possible object is
     *     {@link MarketsT }
     *     
     */
    public MarketsT getMarkets() {
        return markets;
    }

    /**
     * Sets the value of the markets property.
     * 
     * @param value
     *     allowed object is
     *     {@link MarketsT }
     *     
     */
    public void setMarkets(MarketsT value) {
        this.markets = value;
    }

    /**
     * Gets the value of the securityTypes property.
     * 
     * @return
     *     possible object is
     *     {@link SecurityTypesT }
     *     
     */
    public SecurityTypesT getSecurityTypes() {
        return securityTypes;
    }

    /**
     * Sets the value of the securityTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link SecurityTypesT }
     *     
     */
    public void setSecurityTypes(SecurityTypesT value) {
        this.securityTypes = value;
    }

    /**
     * Gets the value of the parameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParameterT }
     * 
     * 
     */
    public List<ParameterT> getParameter() {
        if (parameter == null) {
            parameter = new ArrayList<ParameterT>();
        }
        return this.parameter;
    }

    /**
     * Gets the value of the edit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the edit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEdit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EditT }
     * 
     * 
     */
    public List<EditT> getEdit() {
        if (edit == null) {
            edit = new ArrayList<EditT>();
        }
        return this.edit;
    }

    /**
     * Gets the value of the strategyLayout property.
     * 
     * @return
     *     possible object is
     *     {@link StrategyLayoutT }
     *     
     */
    public StrategyLayoutT getStrategyLayout() {
        return strategyLayout;
    }

    /**
     * Sets the value of the strategyLayout property.
     * 
     * @param value
     *     allowed object is
     *     {@link StrategyLayoutT }
     *     
     */
    public void setStrategyLayout(StrategyLayoutT value) {
        this.strategyLayout = value;
    }

    /**
     * Gets the value of the repeatingGroup property.
     * 
     * @return
     *     possible object is
     *     {@link RepeatingGroupT }
     *     
     */
    public RepeatingGroupT getRepeatingGroup() {
        return repeatingGroup;
    }

    /**
     * Sets the value of the repeatingGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepeatingGroupT }
     *     
     */
    public void setRepeatingGroup(RepeatingGroupT value) {
        this.repeatingGroup = value;
    }

    /**
     * Gets the value of the strategyEdit property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the strategyEdit property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStrategyEdit().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StrategyEditT }
     * 
     * 
     */
    public List<StrategyEditT> getStrategyEdit() {
        if (strategyEdit == null) {
            strategyEdit = new ArrayList<StrategyEditT>();
        }
        return this.strategyEdit;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the uiRep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUiRep() {
        return uiRep;
    }

    /**
     * Sets the value of the uiRep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUiRep(String value) {
        this.uiRep = value;
    }

    /**
     * Gets the value of the wireValue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWireValue() {
        return wireValue;
    }

    /**
     * Sets the value of the wireValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWireValue(String value) {
        this.wireValue = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the fixMsgType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFixMsgType() {
        return fixMsgType;
    }

    /**
     * Sets the value of the fixMsgType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFixMsgType(String value) {
        this.fixMsgType = value;
    }

    /**
     * Gets the value of the disclosureDoc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDisclosureDoc() {
        return disclosureDoc;
    }

    /**
     * Sets the value of the disclosureDoc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDisclosureDoc(String value) {
        this.disclosureDoc = value;
    }

    /**
     * Gets the value of the sentOrderLink property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSentOrderLink() {
        return sentOrderLink;
    }

    /**
     * Sets the value of the sentOrderLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSentOrderLink(String value) {
        this.sentOrderLink = value;
    }

    /**
     * Gets the value of the providerID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderID() {
        return providerID;
    }

    /**
     * Sets the value of the providerID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderID(String value) {
        this.providerID = value;
    }

    /**
     * Gets the value of the providerSubID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProviderSubID() {
        return providerSubID;
    }

    /**
     * Sets the value of the providerSubID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProviderSubID(String value) {
        this.providerSubID = value;
    }

    /**
     * Gets the value of the imageLocation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImageLocation() {
        return imageLocation;
    }

    /**
     * Sets the value of the imageLocation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImageLocation(String value) {
        this.imageLocation = value;
    }

    /**
     * Gets the value of the totalLegs property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalLegs() {
        return totalLegs;
    }

    /**
     * Sets the value of the totalLegs property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalLegs(BigInteger value) {
        this.totalLegs = value;
    }

    /**
     * Gets the value of the totalOrders property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalOrders() {
        return totalOrders;
    }

    /**
     * Sets the value of the totalOrders property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalOrders(BigInteger value) {
        this.totalOrders = value;
    }

    /**
     * Gets the value of the commonIDTag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCommonIDTag() {
        return commonIDTag;
    }

    /**
     * Sets the value of the commonIDTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCommonIDTag(BigInteger value) {
        this.commonIDTag = value;
    }

    /**
     * Gets the value of the totalOrdersTag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getTotalOrdersTag() {
        return totalOrdersTag;
    }

    /**
     * Sets the value of the totalOrdersTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setTotalOrdersTag(BigInteger value) {
        this.totalOrdersTag = value;
    }

    /**
     * Gets the value of the orderSequenceTag property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOrderSequenceTag() {
        return orderSequenceTag;
    }

    /**
     * Sets the value of the orderSequenceTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOrderSequenceTag(BigInteger value) {
        this.orderSequenceTag = value;
    }

}
