//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.30 at 11:18:20 PM JST 
//


package org.atdl4j.atdl.core;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import org.atdl4j.atdl.timezones.Timezone;


/**
 * Derived parameter type corresponding to the FIX "UTCTimestamp" type defined in the FIX specification.
 * 
 * <p>Java class for UTCTimestamp_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UTCTimestamp_t">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.fixprotocol.org/ATDL-1-1/Core}Parameter_t">
 *       &lt;attribute name="minValue" type="{http://www.fixprotocol.org/ATDL-1-1/Core}UTCTimestamp" />
 *       &lt;attribute name="maxValue" type="{http://www.fixprotocol.org/ATDL-1-1/Core}UTCTimestamp" />
 *       &lt;attribute name="constValue" type="{http://www.fixprotocol.org/ATDL-1-1/Core}UTCTimestamp" />
 *       &lt;attribute name="dailyMinValue" type="{http://www.w3.org/2001/XMLSchema}time" />
 *       &lt;attribute name="dailyMaxValue" type="{http://www.w3.org/2001/XMLSchema}time" />
 *       &lt;attribute name="dailyConstValue" type="{http://www.w3.org/2001/XMLSchema}time" />
 *       &lt;attribute name="localMktTz" type="{http://www.fixprotocol.org/ATDL-1-1/Timezones}LocalMktTz_t" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UTCTimestamp_t")
public class UTCTimestampT
    extends ParameterT
{

    @XmlAttribute
    protected XMLGregorianCalendar minValue;
    @XmlAttribute
    protected XMLGregorianCalendar maxValue;
    @XmlAttribute
    protected XMLGregorianCalendar constValue;
    @XmlAttribute
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar dailyMinValue;
    @XmlAttribute
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar dailyMaxValue;
    @XmlAttribute
    @XmlSchemaType(name = "time")
    protected XMLGregorianCalendar dailyConstValue;
    @XmlAttribute
    protected Timezone localMktTz;

    /**
     * Gets the value of the minValue property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMinValue() {
        return minValue;
    }

    /**
     * Sets the value of the minValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMinValue(XMLGregorianCalendar value) {
        this.minValue = value;
    }

    /**
     * Gets the value of the maxValue property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMaxValue() {
        return maxValue;
    }

    /**
     * Sets the value of the maxValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMaxValue(XMLGregorianCalendar value) {
        this.maxValue = value;
    }

    /**
     * Gets the value of the constValue property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getConstValue() {
        return constValue;
    }

    /**
     * Sets the value of the constValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setConstValue(XMLGregorianCalendar value) {
        this.constValue = value;
    }

    /**
     * Gets the value of the dailyMinValue property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDailyMinValue() {
        return dailyMinValue;
    }

    /**
     * Sets the value of the dailyMinValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDailyMinValue(XMLGregorianCalendar value) {
        this.dailyMinValue = value;
    }

    /**
     * Gets the value of the dailyMaxValue property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDailyMaxValue() {
        return dailyMaxValue;
    }

    /**
     * Sets the value of the dailyMaxValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDailyMaxValue(XMLGregorianCalendar value) {
        this.dailyMaxValue = value;
    }

    /**
     * Gets the value of the dailyConstValue property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDailyConstValue() {
        return dailyConstValue;
    }

    /**
     * Sets the value of the dailyConstValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDailyConstValue(XMLGregorianCalendar value) {
        this.dailyConstValue = value;
    }

    /**
     * Gets the value of the localMktTz property.
     * 
     * @return
     *     possible object is
     *     {@link Timezone }
     *     
     */
    public Timezone getLocalMktTz() {
        return localMktTz;
    }

    /**
     * Sets the value of the localMktTz property.
     * 
     * @param value
     *     allowed object is
     *     {@link Timezone }
     *     
     */
    public void setLocalMktTz(Timezone value) {
        this.localMktTz = value;
    }

}
