//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 02:37:55 AM JST 
//


package org.atdl4j.atdl.layout;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import org.atdl4j.atdl.flow.StateRuleT;


/**
 * <p>Java class for ListItem_t complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ListItem_t">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://www.fixprotocol.org/ATDL-1-1/Flow}StateRule" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="enumID" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="uiRep" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ListItem_t", propOrder = {
    "stateRule"
})
public class ListItemT {

    @XmlElement(name = "StateRule", namespace = "http://www.fixprotocol.org/ATDL-1-1/Flow")
    protected List<StateRuleT> stateRule;
    @XmlAttribute
    protected String enumID;
    @XmlAttribute
    protected String uiRep;

    /**
     * Gets the value of the stateRule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stateRule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStateRule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StateRuleT }
     * 
     * 
     */
    public List<StateRuleT> getStateRule() {
        if (stateRule == null) {
            stateRule = new ArrayList<StateRuleT>();
        }
        return this.stateRule;
    }

    /**
     * Gets the value of the enumID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnumID() {
        return enumID;
    }

    /**
     * Sets the value of the enumID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnumID(String value) {
        this.enumID = value;
    }

    /**
     * Gets the value of the uiRep property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUiRep() {
        return uiRep;
    }

    /**
     * Sets the value of the uiRep property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUiRep(String value) {
        this.uiRep = value;
    }

}
