//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.12.07 at 02:37:55 AM JST 
//


package org.atdl4j.atdl.regions;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.atdl4j.atdl.regions package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TheAmericas_QNAME = new QName("http://www.fixprotocol.org/ATDL-1-1/Regions", "TheAmericas");
    private final static QName _AsiaPacificJapan_QNAME = new QName("http://www.fixprotocol.org/ATDL-1-1/Regions", "AsiaPacificJapan");
    private final static QName _EuropeMiddleEastAfrica_QNAME = new QName("http://www.fixprotocol.org/ATDL-1-1/Regions", "EuropeMiddleEastAfrica");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.atdl4j.atdl.regions
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/ATDL-1-1/Regions", name = "TheAmericas")
    public JAXBElement<String> createTheAmericas(String value) {
        return new JAXBElement<String>(_TheAmericas_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/ATDL-1-1/Regions", name = "AsiaPacificJapan")
    public JAXBElement<String> createAsiaPacificJapan(String value) {
        return new JAXBElement<String>(_AsiaPacificJapan_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/ATDL-1-1/Regions", name = "EuropeMiddleEastAfrica")
    public JAXBElement<String> createEuropeMiddleEastAfrica(String value) {
        return new JAXBElement<String>(_EuropeMiddleEastAfrica_QNAME, String.class, null, value);
    }

}
