//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 10:55:05 AM CST 
//


package org.atdl4j.fixatdl.regions;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.atdl4j.fixatdl.regions package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _TheAmericas_QNAME = new QName("http://www.fixprotocol.org/FIXatdl-1-1/Regions", "TheAmericas");
    private static final QName _AsiaPacificJapan_QNAME = new QName("http://www.fixprotocol.org/FIXatdl-1-1/Regions", "AsiaPacificJapan");
    private static final QName _EuropeMiddleEastAfrica_QNAME = new QName("http://www.fixprotocol.org/FIXatdl-1-1/Regions", "EuropeMiddleEastAfrica");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.atdl4j.fixatdl.regions
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TheAmericas }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXatdl-1-1/Regions", name = "TheAmericas")
    public JAXBElement<TheAmericas> createTheAmericas(TheAmericas value) {
        return new JAXBElement<>(_TheAmericas_QNAME, TheAmericas.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AsiaPacificJapan }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXatdl-1-1/Regions", name = "AsiaPacificJapan")
    public JAXBElement<AsiaPacificJapan> createAsiaPacificJapan(AsiaPacificJapan value) {
        return new JAXBElement<>(_AsiaPacificJapan_QNAME, AsiaPacificJapan.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EuropeMiddleEastAfrica }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXatdl-1-1/Regions", name = "EuropeMiddleEastAfrica")
    public JAXBElement<EuropeMiddleEastAfrica> createEuropeMiddleEastAfrica(EuropeMiddleEastAfrica value) {
        return new JAXBElement<>(_EuropeMiddleEastAfrica_QNAME, EuropeMiddleEastAfrica.class, null, value);
    }

}
