//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 10:55:05 AM CST 
//


package org.atdl4j.fixatdl.regions;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for null.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType>
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="AF"/>
 *     &lt;enumeration value="AS"/>
 *     &lt;enumeration value="AU"/>
 *     &lt;enumeration value="BD"/>
 *     &lt;enumeration value="BT"/>
 *     &lt;enumeration value="IO"/>
 *     &lt;enumeration value="BN"/>
 *     &lt;enumeration value="KH"/>
 *     &lt;enumeration value="CN"/>
 *     &lt;enumeration value="CX"/>
 *     &lt;enumeration value="CC"/>
 *     &lt;enumeration value="CK"/>
 *     &lt;enumeration value="FJ"/>
 *     &lt;enumeration value="PF"/>
 *     &lt;enumeration value="GU"/>
 *     &lt;enumeration value="HK"/>
 *     &lt;enumeration value="IN"/>
 *     &lt;enumeration value="ID"/>
 *     &lt;enumeration value="JP"/>
 *     &lt;enumeration value="KZ"/>
 *     &lt;enumeration value="KI"/>
 *     &lt;enumeration value="KP"/>
 *     &lt;enumeration value="KR"/>
 *     &lt;enumeration value="KG"/>
 *     &lt;enumeration value="LA"/>
 *     &lt;enumeration value="MO"/>
 *     &lt;enumeration value="MY"/>
 *     &lt;enumeration value="MV"/>
 *     &lt;enumeration value="MH"/>
 *     &lt;enumeration value="FM"/>
 *     &lt;enumeration value="MN"/>
 *     &lt;enumeration value="MM"/>
 *     &lt;enumeration value="NR"/>
 *     &lt;enumeration value="NP"/>
 *     &lt;enumeration value="NC"/>
 *     &lt;enumeration value="NZ"/>
 *     &lt;enumeration value="NU"/>
 *     &lt;enumeration value="NF"/>
 *     &lt;enumeration value="MP"/>
 *     &lt;enumeration value="PK"/>
 *     &lt;enumeration value="PW"/>
 *     &lt;enumeration value="PG"/>
 *     &lt;enumeration value="PH"/>
 *     &lt;enumeration value="WS"/>
 *     &lt;enumeration value="SG"/>
 *     &lt;enumeration value="SB"/>
 *     &lt;enumeration value="TW"/>
 *     &lt;enumeration value="TJ"/>
 *     &lt;enumeration value="TH"/>
 *     &lt;enumeration value="TL"/>
 *     &lt;enumeration value="TK"/>
 *     &lt;enumeration value="TO"/>
 *     &lt;enumeration value="TM"/>
 *     &lt;enumeration value="TV"/>
 *     &lt;enumeration value="UM"/>
 *     &lt;enumeration value="UZ"/>
 *     &lt;enumeration value="VU"/>
 *     &lt;enumeration value="VN"/>
 *     &lt;enumeration value="WF"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "")
@XmlEnum
public enum AsiaPacificJapan {

    AF,
    AS,
    AU,
    BD,
    BT,
    IO,
    BN,
    KH,
    CN,
    CX,
    CC,
    CK,
    FJ,
    PF,
    GU,
    HK,
    IN,
    ID,
    JP,
    KZ,
    KI,
    KP,
    KR,
    KG,
    LA,
    MO,
    MY,
    MV,
    MH,
    FM,
    MN,
    MM,
    NR,
    NP,
    NC,
    NZ,
    NU,
    NF,
    MP,
    PK,
    PW,
    PG,
    PH,
    WS,
    SG,
    SB,
    TW,
    TJ,
    TH,
    TL,
    TK,
    TO,
    TM,
    TV,
    UM,
    UZ,
    VU,
    VN,
    WF;

    public String value() {
        return name();
    }

    public static AsiaPacificJapan fromValue(String v) {
        return valueOf(v);
    }

}
