//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-548 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.01.30 at 11:18:20 PM JST 
//


package org.atdl4j.atdl.timezones;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LocalMktTz_t.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LocalMktTz_t">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Africa/Abidjan"/>
 *     &lt;enumeration value="Africa/Accra"/>
 *     &lt;enumeration value="Africa/Addis_Ababa"/>
 *     &lt;enumeration value="Africa/Algiers"/>
 *     &lt;enumeration value="Africa/Asmara"/>
 *     &lt;enumeration value="Africa/Bamako"/>
 *     &lt;enumeration value="Africa/Bangui"/>
 *     &lt;enumeration value="Africa/Banjul"/>
 *     &lt;enumeration value="Africa/Bissau"/>
 *     &lt;enumeration value="Africa/Blantyre"/>
 *     &lt;enumeration value="Africa/Brazzaville"/>
 *     &lt;enumeration value="Africa/Bujumbura"/>
 *     &lt;enumeration value="Africa/Cairo"/>
 *     &lt;enumeration value="Africa/Casablanca"/>
 *     &lt;enumeration value="Africa/Ceuta"/>
 *     &lt;enumeration value="Africa/Conakry"/>
 *     &lt;enumeration value="Africa/Dakar"/>
 *     &lt;enumeration value="Africa/Dar_es_Salaam"/>
 *     &lt;enumeration value="Africa/Djibouti"/>
 *     &lt;enumeration value="Africa/Douala"/>
 *     &lt;enumeration value="Africa/El_Aaiun"/>
 *     &lt;enumeration value="Africa/Freetown"/>
 *     &lt;enumeration value="Africa/Gaborone"/>
 *     &lt;enumeration value="Africa/Harare"/>
 *     &lt;enumeration value="Africa/Johannesburg"/>
 *     &lt;enumeration value="Africa/Kampala"/>
 *     &lt;enumeration value="Africa/Khartoum"/>
 *     &lt;enumeration value="Africa/Kigali"/>
 *     &lt;enumeration value="Africa/Kinshasa"/>
 *     &lt;enumeration value="Africa/Lagos"/>
 *     &lt;enumeration value="Africa/Libreville"/>
 *     &lt;enumeration value="Africa/Lome"/>
 *     &lt;enumeration value="Africa/Luanda"/>
 *     &lt;enumeration value="Africa/Lubumbashi"/>
 *     &lt;enumeration value="Africa/Lusaka"/>
 *     &lt;enumeration value="Africa/Malabo"/>
 *     &lt;enumeration value="Africa/Maputo"/>
 *     &lt;enumeration value="Africa/Maseru"/>
 *     &lt;enumeration value="Africa/Mbabane"/>
 *     &lt;enumeration value="Africa/Mogadishu"/>
 *     &lt;enumeration value="Africa/Monrovia"/>
 *     &lt;enumeration value="Africa/Nairobi"/>
 *     &lt;enumeration value="Africa/Ndjamena"/>
 *     &lt;enumeration value="Africa/Niamey"/>
 *     &lt;enumeration value="Africa/Nouakchott"/>
 *     &lt;enumeration value="Africa/Ouagadougou"/>
 *     &lt;enumeration value="Africa/Porto-Novo"/>
 *     &lt;enumeration value="Africa/Sao_Tome"/>
 *     &lt;enumeration value="Africa/Tripoli"/>
 *     &lt;enumeration value="Africa/Tunis"/>
 *     &lt;enumeration value="Africa/Windhoek"/>
 *     &lt;enumeration value="America/Adak"/>
 *     &lt;enumeration value="America/Anchorage"/>
 *     &lt;enumeration value="America/Anguilla"/>
 *     &lt;enumeration value="America/Antigua"/>
 *     &lt;enumeration value="America/Araguaina"/>
 *     &lt;enumeration value="America/Argentina/Buenos_Aires"/>
 *     &lt;enumeration value="America/Argentina/Catamarca"/>
 *     &lt;enumeration value="America/Argentina/Cordoba"/>
 *     &lt;enumeration value="America/Argentina/Jujuy"/>
 *     &lt;enumeration value="America/Argentina/La_Rioja"/>
 *     &lt;enumeration value="America/Argentina/Mendoza"/>
 *     &lt;enumeration value="America/Argentina/Rio_Gallegos"/>
 *     &lt;enumeration value="America/Argentina/Salta"/>
 *     &lt;enumeration value="America/Argentina/San_Juan"/>
 *     &lt;enumeration value="America/Argentina/San_Luis"/>
 *     &lt;enumeration value="America/Argentina/Tucuman"/>
 *     &lt;enumeration value="America/Argentina/Ushuaia"/>
 *     &lt;enumeration value="America/Aruba"/>
 *     &lt;enumeration value="America/Asuncion"/>
 *     &lt;enumeration value="America/Atikokan"/>
 *     &lt;enumeration value="America/Bahia"/>
 *     &lt;enumeration value="America/Barbados"/>
 *     &lt;enumeration value="America/Belem"/>
 *     &lt;enumeration value="America/Belize"/>
 *     &lt;enumeration value="America/Blanc-Sablon"/>
 *     &lt;enumeration value="America/Boa_Vista"/>
 *     &lt;enumeration value="America/Bogota"/>
 *     &lt;enumeration value="America/Boise"/>
 *     &lt;enumeration value="America/Cambridge_Bay"/>
 *     &lt;enumeration value="America/Campo_Grande"/>
 *     &lt;enumeration value="America/Cancun"/>
 *     &lt;enumeration value="America/Caracas"/>
 *     &lt;enumeration value="America/Cayenne"/>
 *     &lt;enumeration value="America/Cayman"/>
 *     &lt;enumeration value="America/Chicago"/>
 *     &lt;enumeration value="America/Chihuahua"/>
 *     &lt;enumeration value="America/Costa_Rica"/>
 *     &lt;enumeration value="America/Cuiaba"/>
 *     &lt;enumeration value="America/Curacao"/>
 *     &lt;enumeration value="America/Danmarkshavn"/>
 *     &lt;enumeration value="America/Dawson"/>
 *     &lt;enumeration value="America/Dawson_Creek"/>
 *     &lt;enumeration value="America/Denver"/>
 *     &lt;enumeration value="America/Detroit"/>
 *     &lt;enumeration value="America/Dominica"/>
 *     &lt;enumeration value="America/Edmonton"/>
 *     &lt;enumeration value="America/Eirunepe"/>
 *     &lt;enumeration value="America/El_Salvador"/>
 *     &lt;enumeration value="America/Fortaleza"/>
 *     &lt;enumeration value="America/Glace_Bay"/>
 *     &lt;enumeration value="America/Godthab"/>
 *     &lt;enumeration value="America/Goose_Bay"/>
 *     &lt;enumeration value="America/Grand_Turk"/>
 *     &lt;enumeration value="America/Grenada"/>
 *     &lt;enumeration value="America/Guadeloupe"/>
 *     &lt;enumeration value="America/Guatemala"/>
 *     &lt;enumeration value="America/Guayaquil"/>
 *     &lt;enumeration value="America/Guyana"/>
 *     &lt;enumeration value="America/Halifax"/>
 *     &lt;enumeration value="America/Havana"/>
 *     &lt;enumeration value="America/Hermosillo"/>
 *     &lt;enumeration value="America/Indiana/Indianapolis"/>
 *     &lt;enumeration value="America/Indiana/Knox"/>
 *     &lt;enumeration value="America/Indiana/Marengo"/>
 *     &lt;enumeration value="America/Indiana/Petersburg"/>
 *     &lt;enumeration value="America/Indiana/Tell_City"/>
 *     &lt;enumeration value="America/Indiana/Vevay"/>
 *     &lt;enumeration value="America/Indiana/Vincennes"/>
 *     &lt;enumeration value="America/Indiana/Winamac"/>
 *     &lt;enumeration value="America/Inuvik"/>
 *     &lt;enumeration value="America/Iqaluit"/>
 *     &lt;enumeration value="America/Jamaica"/>
 *     &lt;enumeration value="America/Juneau"/>
 *     &lt;enumeration value="America/Kentucky/Louisville"/>
 *     &lt;enumeration value="America/Kentucky/Monticello"/>
 *     &lt;enumeration value="America/La_Paz"/>
 *     &lt;enumeration value="America/Lima"/>
 *     &lt;enumeration value="America/Los_Angeles"/>
 *     &lt;enumeration value="America/Maceio"/>
 *     &lt;enumeration value="America/Managua"/>
 *     &lt;enumeration value="America/Manaus"/>
 *     &lt;enumeration value="America/Marigot"/>
 *     &lt;enumeration value="America/Martinique"/>
 *     &lt;enumeration value="America/Mazatlan"/>
 *     &lt;enumeration value="America/Menominee"/>
 *     &lt;enumeration value="America/Merida"/>
 *     &lt;enumeration value="America/Mexico_City"/>
 *     &lt;enumeration value="America/Miquelon"/>
 *     &lt;enumeration value="America/Moncton"/>
 *     &lt;enumeration value="America/Monterrey"/>
 *     &lt;enumeration value="America/Montevideo"/>
 *     &lt;enumeration value="America/Montreal"/>
 *     &lt;enumeration value="America/Montserrat"/>
 *     &lt;enumeration value="America/Nassau"/>
 *     &lt;enumeration value="America/New_York"/>
 *     &lt;enumeration value="America/Nipigon"/>
 *     &lt;enumeration value="America/Nome"/>
 *     &lt;enumeration value="America/Noronha"/>
 *     &lt;enumeration value="America/North_Dakota/Center"/>
 *     &lt;enumeration value="America/North_Dakota/New_Salem"/>
 *     &lt;enumeration value="America/Panama"/>
 *     &lt;enumeration value="America/Pangnirtung"/>
 *     &lt;enumeration value="America/Paramaribo"/>
 *     &lt;enumeration value="America/Phoenix"/>
 *     &lt;enumeration value="America/Port-au-Prince"/>
 *     &lt;enumeration value="America/Port_of_Spain"/>
 *     &lt;enumeration value="America/Porto_Velho"/>
 *     &lt;enumeration value="America/Puerto_Rico"/>
 *     &lt;enumeration value="America/Rainy_River"/>
 *     &lt;enumeration value="America/Rankin_Inlet"/>
 *     &lt;enumeration value="America/Recife"/>
 *     &lt;enumeration value="America/Regina"/>
 *     &lt;enumeration value="America/Resolute"/>
 *     &lt;enumeration value="America/Rio_Branco"/>
 *     &lt;enumeration value="America/Santarem"/>
 *     &lt;enumeration value="America/Santiago"/>
 *     &lt;enumeration value="America/Santo_Domingo"/>
 *     &lt;enumeration value="America/Sao_Paulo"/>
 *     &lt;enumeration value="America/Scoresbysund"/>
 *     &lt;enumeration value="America/Shiprock"/>
 *     &lt;enumeration value="America/St_Barthelemy"/>
 *     &lt;enumeration value="America/St_Johns"/>
 *     &lt;enumeration value="America/St_Kitts"/>
 *     &lt;enumeration value="America/St_Lucia"/>
 *     &lt;enumeration value="America/St_Thomas"/>
 *     &lt;enumeration value="America/St_Vincent"/>
 *     &lt;enumeration value="America/Swift_Current"/>
 *     &lt;enumeration value="America/Tegucigalpa"/>
 *     &lt;enumeration value="America/Thule"/>
 *     &lt;enumeration value="America/Thunder_Bay"/>
 *     &lt;enumeration value="America/Tijuana"/>
 *     &lt;enumeration value="America/Toronto"/>
 *     &lt;enumeration value="America/Tortola"/>
 *     &lt;enumeration value="America/Vancouver"/>
 *     &lt;enumeration value="America/Whitehorse"/>
 *     &lt;enumeration value="America/Winnipeg"/>
 *     &lt;enumeration value="America/Yakutat"/>
 *     &lt;enumeration value="America/Yellowknife"/>
 *     &lt;enumeration value="Antarctica/Casey"/>
 *     &lt;enumeration value="Antarctica/Davis"/>
 *     &lt;enumeration value="Antarctica/DumontDUrville"/>
 *     &lt;enumeration value="Antarctica/Mawson"/>
 *     &lt;enumeration value="Antarctica/McMurdo"/>
 *     &lt;enumeration value="Antarctica/Palmer"/>
 *     &lt;enumeration value="Antarctica/Rothera"/>
 *     &lt;enumeration value="Antarctica/South_Pole"/>
 *     &lt;enumeration value="Antarctica/Syowa"/>
 *     &lt;enumeration value="Antarctica/Vostok"/>
 *     &lt;enumeration value="Arctic/Longyearbyen"/>
 *     &lt;enumeration value="Asia/Aden"/>
 *     &lt;enumeration value="Asia/Almaty"/>
 *     &lt;enumeration value="Asia/Amman"/>
 *     &lt;enumeration value="Asia/Anadyr"/>
 *     &lt;enumeration value="Asia/Aqtau"/>
 *     &lt;enumeration value="Asia/Aqtobe"/>
 *     &lt;enumeration value="Asia/Ashgabat"/>
 *     &lt;enumeration value="Asia/Baghdad"/>
 *     &lt;enumeration value="Asia/Bahrain"/>
 *     &lt;enumeration value="Asia/Baku"/>
 *     &lt;enumeration value="Asia/Bangkok"/>
 *     &lt;enumeration value="Asia/Beirut"/>
 *     &lt;enumeration value="Asia/Bishkek"/>
 *     &lt;enumeration value="Asia/Brunei"/>
 *     &lt;enumeration value="Asia/Choibalsan"/>
 *     &lt;enumeration value="Asia/Chongqing"/>
 *     &lt;enumeration value="Asia/Colombo"/>
 *     &lt;enumeration value="Asia/Damascus"/>
 *     &lt;enumeration value="Asia/Dhaka"/>
 *     &lt;enumeration value="Asia/Dili"/>
 *     &lt;enumeration value="Asia/Dubai"/>
 *     &lt;enumeration value="Asia/Dushanbe"/>
 *     &lt;enumeration value="Asia/Gaza"/>
 *     &lt;enumeration value="Asia/Harbin"/>
 *     &lt;enumeration value="Asia/Ho_Chi_Minh"/>
 *     &lt;enumeration value="Asia/Hong_Kong"/>
 *     &lt;enumeration value="Asia/Hovd"/>
 *     &lt;enumeration value="Asia/Irkutsk"/>
 *     &lt;enumeration value="Asia/Jakarta"/>
 *     &lt;enumeration value="Asia/Jayapura"/>
 *     &lt;enumeration value="Asia/Jerusalem"/>
 *     &lt;enumeration value="Asia/Kabul"/>
 *     &lt;enumeration value="Asia/Kamchatka"/>
 *     &lt;enumeration value="Asia/Karachi"/>
 *     &lt;enumeration value="Asia/Kashgar"/>
 *     &lt;enumeration value="Asia/Katmandu"/>
 *     &lt;enumeration value="Asia/Kolkata"/>
 *     &lt;enumeration value="Asia/Krasnoyarsk"/>
 *     &lt;enumeration value="Asia/Kuala_Lumpur"/>
 *     &lt;enumeration value="Asia/Kuching"/>
 *     &lt;enumeration value="Asia/Kuwait"/>
 *     &lt;enumeration value="Asia/Macau"/>
 *     &lt;enumeration value="Asia/Magadan"/>
 *     &lt;enumeration value="Asia/Makassar"/>
 *     &lt;enumeration value="Asia/Manila"/>
 *     &lt;enumeration value="Asia/Muscat"/>
 *     &lt;enumeration value="Asia/Nicosia"/>
 *     &lt;enumeration value="Asia/Novosibirsk"/>
 *     &lt;enumeration value="Asia/Omsk"/>
 *     &lt;enumeration value="Asia/Oral"/>
 *     &lt;enumeration value="Asia/Phnom_Penh"/>
 *     &lt;enumeration value="Asia/Pontianak"/>
 *     &lt;enumeration value="Asia/Pyongyang"/>
 *     &lt;enumeration value="Asia/Qatar"/>
 *     &lt;enumeration value="Asia/Qyzylorda"/>
 *     &lt;enumeration value="Asia/Rangoon"/>
 *     &lt;enumeration value="Asia/Riyadh"/>
 *     &lt;enumeration value="Asia/Sakhalin"/>
 *     &lt;enumeration value="Asia/Samarkand"/>
 *     &lt;enumeration value="Asia/Seoul"/>
 *     &lt;enumeration value="Asia/Shanghai"/>
 *     &lt;enumeration value="Asia/Singapore"/>
 *     &lt;enumeration value="Asia/Taipei"/>
 *     &lt;enumeration value="Asia/Tashkent"/>
 *     &lt;enumeration value="Asia/Tbilisi"/>
 *     &lt;enumeration value="Asia/Tehran"/>
 *     &lt;enumeration value="Asia/Thimphu"/>
 *     &lt;enumeration value="Asia/Tokyo"/>
 *     &lt;enumeration value="Asia/Ulaanbaatar"/>
 *     &lt;enumeration value="Asia/Urumqi"/>
 *     &lt;enumeration value="Asia/Vientiane"/>
 *     &lt;enumeration value="Asia/Vladivostok"/>
 *     &lt;enumeration value="Asia/Yakutsk"/>
 *     &lt;enumeration value="Asia/Yekaterinburg"/>
 *     &lt;enumeration value="Asia/Yerevan"/>
 *     &lt;enumeration value="Atlantic/Azores"/>
 *     &lt;enumeration value="Atlantic/Bermuda"/>
 *     &lt;enumeration value="Atlantic/Canary"/>
 *     &lt;enumeration value="Atlantic/Cape_Verde"/>
 *     &lt;enumeration value="Atlantic/Faroe"/>
 *     &lt;enumeration value="Atlantic/Madeira"/>
 *     &lt;enumeration value="Atlantic/Reykjavik"/>
 *     &lt;enumeration value="Atlantic/South_Georgia"/>
 *     &lt;enumeration value="Atlantic/St_Helena"/>
 *     &lt;enumeration value="Atlantic/Stanley"/>
 *     &lt;enumeration value="Australia/Adelaide"/>
 *     &lt;enumeration value="Australia/Brisbane"/>
 *     &lt;enumeration value="Australia/Broken_Hill"/>
 *     &lt;enumeration value="Australia/Currie"/>
 *     &lt;enumeration value="Australia/Darwin"/>
 *     &lt;enumeration value="Australia/Eucla"/>
 *     &lt;enumeration value="Australia/Hobart"/>
 *     &lt;enumeration value="Australia/Lindeman"/>
 *     &lt;enumeration value="Australia/Lord_Howe"/>
 *     &lt;enumeration value="Australia/Melbourne"/>
 *     &lt;enumeration value="Australia/Perth"/>
 *     &lt;enumeration value="Australia/Sydney"/>
 *     &lt;enumeration value="Europe/Amsterdam"/>
 *     &lt;enumeration value="Europe/Andorra"/>
 *     &lt;enumeration value="Europe/Athens"/>
 *     &lt;enumeration value="Europe/Belgrade"/>
 *     &lt;enumeration value="Europe/Berlin"/>
 *     &lt;enumeration value="Europe/Bratislava"/>
 *     &lt;enumeration value="Europe/Brussels"/>
 *     &lt;enumeration value="Europe/Bucharest"/>
 *     &lt;enumeration value="Europe/Budapest"/>
 *     &lt;enumeration value="Europe/Chisinau"/>
 *     &lt;enumeration value="Europe/Copenhagen"/>
 *     &lt;enumeration value="Europe/Dublin"/>
 *     &lt;enumeration value="Europe/Gibraltar"/>
 *     &lt;enumeration value="Europe/Guernsey"/>
 *     &lt;enumeration value="Europe/Helsinki"/>
 *     &lt;enumeration value="Europe/Isle_of_Man"/>
 *     &lt;enumeration value="Europe/Istanbul"/>
 *     &lt;enumeration value="Europe/Jersey"/>
 *     &lt;enumeration value="Europe/Kaliningrad"/>
 *     &lt;enumeration value="Europe/Kiev"/>
 *     &lt;enumeration value="Europe/Lisbon"/>
 *     &lt;enumeration value="Europe/Ljubljana"/>
 *     &lt;enumeration value="Europe/London"/>
 *     &lt;enumeration value="Europe/Luxembourg"/>
 *     &lt;enumeration value="Europe/Madrid"/>
 *     &lt;enumeration value="Europe/Malta"/>
 *     &lt;enumeration value="Europe/Mariehamn"/>
 *     &lt;enumeration value="Europe/Minsk"/>
 *     &lt;enumeration value="Europe/Monaco"/>
 *     &lt;enumeration value="Europe/Moscow"/>
 *     &lt;enumeration value="Europe/Oslo"/>
 *     &lt;enumeration value="Europe/Paris"/>
 *     &lt;enumeration value="Europe/Podgorica"/>
 *     &lt;enumeration value="Europe/Prague"/>
 *     &lt;enumeration value="Europe/Riga"/>
 *     &lt;enumeration value="Europe/Rome"/>
 *     &lt;enumeration value="Europe/Samara"/>
 *     &lt;enumeration value="Europe/San_Marino"/>
 *     &lt;enumeration value="Europe/Sarajevo"/>
 *     &lt;enumeration value="Europe/Simferopol"/>
 *     &lt;enumeration value="Europe/Skopje"/>
 *     &lt;enumeration value="Europe/Sofia"/>
 *     &lt;enumeration value="Europe/Stockholm"/>
 *     &lt;enumeration value="Europe/Tallinn"/>
 *     &lt;enumeration value="Europe/Tirane"/>
 *     &lt;enumeration value="Europe/Uzhgorod"/>
 *     &lt;enumeration value="Europe/Vaduz"/>
 *     &lt;enumeration value="Europe/Vatican"/>
 *     &lt;enumeration value="Europe/Vienna"/>
 *     &lt;enumeration value="Europe/Vilnius"/>
 *     &lt;enumeration value="Europe/Volgograd"/>
 *     &lt;enumeration value="Europe/Warsaw"/>
 *     &lt;enumeration value="Europe/Zagreb"/>
 *     &lt;enumeration value="Europe/Zaporozhye"/>
 *     &lt;enumeration value="Europe/Zurich"/>
 *     &lt;enumeration value="Indian/Antananarivo"/>
 *     &lt;enumeration value="Indian/Chagos"/>
 *     &lt;enumeration value="Indian/Christmas"/>
 *     &lt;enumeration value="Indian/Cocos"/>
 *     &lt;enumeration value="Indian/Comoro"/>
 *     &lt;enumeration value="Indian/Kerguelen"/>
 *     &lt;enumeration value="Indian/Mahe"/>
 *     &lt;enumeration value="Indian/Maldives"/>
 *     &lt;enumeration value="Indian/Mauritius"/>
 *     &lt;enumeration value="Indian/Mayotte"/>
 *     &lt;enumeration value="Indian/Reunion"/>
 *     &lt;enumeration value="Pacific/Apia"/>
 *     &lt;enumeration value="Pacific/Auckland"/>
 *     &lt;enumeration value="Pacific/Chatham"/>
 *     &lt;enumeration value="Pacific/Easter"/>
 *     &lt;enumeration value="Pacific/Efate"/>
 *     &lt;enumeration value="Pacific/Enderbury"/>
 *     &lt;enumeration value="Pacific/Fakaofo"/>
 *     &lt;enumeration value="Pacific/Fiji"/>
 *     &lt;enumeration value="Pacific/Funafuti"/>
 *     &lt;enumeration value="Pacific/Galapagos"/>
 *     &lt;enumeration value="Pacific/Gambier"/>
 *     &lt;enumeration value="Pacific/Guadalcanal"/>
 *     &lt;enumeration value="Pacific/Guam"/>
 *     &lt;enumeration value="Pacific/Honolulu"/>
 *     &lt;enumeration value="Pacific/Johnston"/>
 *     &lt;enumeration value="Pacific/Kiritimati"/>
 *     &lt;enumeration value="Pacific/Kosrae"/>
 *     &lt;enumeration value="Pacific/Kwajalein"/>
 *     &lt;enumeration value="Pacific/Majuro"/>
 *     &lt;enumeration value="Pacific/Marquesas"/>
 *     &lt;enumeration value="Pacific/Midway"/>
 *     &lt;enumeration value="Pacific/Nauru"/>
 *     &lt;enumeration value="Pacific/Niue"/>
 *     &lt;enumeration value="Pacific/Norfolk"/>
 *     &lt;enumeration value="Pacific/Noumea"/>
 *     &lt;enumeration value="Pacific/Pago_Pago"/>
 *     &lt;enumeration value="Pacific/Palau"/>
 *     &lt;enumeration value="Pacific/Pitcairn"/>
 *     &lt;enumeration value="Pacific/Ponape"/>
 *     &lt;enumeration value="Pacific/Port_Moresby"/>
 *     &lt;enumeration value="Pacific/Rarotonga"/>
 *     &lt;enumeration value="Pacific/Saipan"/>
 *     &lt;enumeration value="Pacific/Tahiti"/>
 *     &lt;enumeration value="Pacific/Tarawa"/>
 *     &lt;enumeration value="Pacific/Tongatapu"/>
 *     &lt;enumeration value="Pacific/Truk"/>
 *     &lt;enumeration value="Pacific/Wake"/>
 *     &lt;enumeration value="Pacific/Wallis"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LocalMktTz_t", namespace = "http://www.fixprotocol.org/ATDL-1-1/Timezones")
@XmlEnum
public enum Timezone {

    @XmlEnumValue("Africa/Abidjan")
    AFRICA_ABIDJAN("Africa/Abidjan"),
    @XmlEnumValue("Africa/Accra")
    AFRICA_ACCRA("Africa/Accra"),
    @XmlEnumValue("Africa/Addis_Ababa")
    AFRICA_ADDIS_ABABA("Africa/Addis_Ababa"),
    @XmlEnumValue("Africa/Algiers")
    AFRICA_ALGIERS("Africa/Algiers"),
    @XmlEnumValue("Africa/Asmara")
    AFRICA_ASMARA("Africa/Asmara"),
    @XmlEnumValue("Africa/Bamako")
    AFRICA_BAMAKO("Africa/Bamako"),
    @XmlEnumValue("Africa/Bangui")
    AFRICA_BANGUI("Africa/Bangui"),
    @XmlEnumValue("Africa/Banjul")
    AFRICA_BANJUL("Africa/Banjul"),
    @XmlEnumValue("Africa/Bissau")
    AFRICA_BISSAU("Africa/Bissau"),
    @XmlEnumValue("Africa/Blantyre")
    AFRICA_BLANTYRE("Africa/Blantyre"),
    @XmlEnumValue("Africa/Brazzaville")
    AFRICA_BRAZZAVILLE("Africa/Brazzaville"),
    @XmlEnumValue("Africa/Bujumbura")
    AFRICA_BUJUMBURA("Africa/Bujumbura"),
    @XmlEnumValue("Africa/Cairo")
    AFRICA_CAIRO("Africa/Cairo"),
    @XmlEnumValue("Africa/Casablanca")
    AFRICA_CASABLANCA("Africa/Casablanca"),
    @XmlEnumValue("Africa/Ceuta")
    AFRICA_CEUTA("Africa/Ceuta"),
    @XmlEnumValue("Africa/Conakry")
    AFRICA_CONAKRY("Africa/Conakry"),
    @XmlEnumValue("Africa/Dakar")
    AFRICA_DAKAR("Africa/Dakar"),
    @XmlEnumValue("Africa/Dar_es_Salaam")
    AFRICA_DAR_ES_SALAAM("Africa/Dar_es_Salaam"),
    @XmlEnumValue("Africa/Djibouti")
    AFRICA_DJIBOUTI("Africa/Djibouti"),
    @XmlEnumValue("Africa/Douala")
    AFRICA_DOUALA("Africa/Douala"),
    @XmlEnumValue("Africa/El_Aaiun")
    AFRICA_EL_AAIUN("Africa/El_Aaiun"),
    @XmlEnumValue("Africa/Freetown")
    AFRICA_FREETOWN("Africa/Freetown"),
    @XmlEnumValue("Africa/Gaborone")
    AFRICA_GABORONE("Africa/Gaborone"),
    @XmlEnumValue("Africa/Harare")
    AFRICA_HARARE("Africa/Harare"),
    @XmlEnumValue("Africa/Johannesburg")
    AFRICA_JOHANNESBURG("Africa/Johannesburg"),
    @XmlEnumValue("Africa/Kampala")
    AFRICA_KAMPALA("Africa/Kampala"),
    @XmlEnumValue("Africa/Khartoum")
    AFRICA_KHARTOUM("Africa/Khartoum"),
    @XmlEnumValue("Africa/Kigali")
    AFRICA_KIGALI("Africa/Kigali"),
    @XmlEnumValue("Africa/Kinshasa")
    AFRICA_KINSHASA("Africa/Kinshasa"),
    @XmlEnumValue("Africa/Lagos")
    AFRICA_LAGOS("Africa/Lagos"),
    @XmlEnumValue("Africa/Libreville")
    AFRICA_LIBREVILLE("Africa/Libreville"),
    @XmlEnumValue("Africa/Lome")
    AFRICA_LOME("Africa/Lome"),
    @XmlEnumValue("Africa/Luanda")
    AFRICA_LUANDA("Africa/Luanda"),
    @XmlEnumValue("Africa/Lubumbashi")
    AFRICA_LUBUMBASHI("Africa/Lubumbashi"),
    @XmlEnumValue("Africa/Lusaka")
    AFRICA_LUSAKA("Africa/Lusaka"),
    @XmlEnumValue("Africa/Malabo")
    AFRICA_MALABO("Africa/Malabo"),
    @XmlEnumValue("Africa/Maputo")
    AFRICA_MAPUTO("Africa/Maputo"),
    @XmlEnumValue("Africa/Maseru")
    AFRICA_MASERU("Africa/Maseru"),
    @XmlEnumValue("Africa/Mbabane")
    AFRICA_MBABANE("Africa/Mbabane"),
    @XmlEnumValue("Africa/Mogadishu")
    AFRICA_MOGADISHU("Africa/Mogadishu"),
    @XmlEnumValue("Africa/Monrovia")
    AFRICA_MONROVIA("Africa/Monrovia"),
    @XmlEnumValue("Africa/Nairobi")
    AFRICA_NAIROBI("Africa/Nairobi"),
    @XmlEnumValue("Africa/Ndjamena")
    AFRICA_NDJAMENA("Africa/Ndjamena"),
    @XmlEnumValue("Africa/Niamey")
    AFRICA_NIAMEY("Africa/Niamey"),
    @XmlEnumValue("Africa/Nouakchott")
    AFRICA_NOUAKCHOTT("Africa/Nouakchott"),
    @XmlEnumValue("Africa/Ouagadougou")
    AFRICA_OUAGADOUGOU("Africa/Ouagadougou"),
    @XmlEnumValue("Africa/Porto-Novo")
    AFRICA_PORTO_NOVO("Africa/Porto-Novo"),
    @XmlEnumValue("Africa/Sao_Tome")
    AFRICA_SAO_TOME("Africa/Sao_Tome"),
    @XmlEnumValue("Africa/Tripoli")
    AFRICA_TRIPOLI("Africa/Tripoli"),
    @XmlEnumValue("Africa/Tunis")
    AFRICA_TUNIS("Africa/Tunis"),
    @XmlEnumValue("Africa/Windhoek")
    AFRICA_WINDHOEK("Africa/Windhoek"),
    @XmlEnumValue("America/Adak")
    AMERICA_ADAK("America/Adak"),
    @XmlEnumValue("America/Anchorage")
    AMERICA_ANCHORAGE("America/Anchorage"),
    @XmlEnumValue("America/Anguilla")
    AMERICA_ANGUILLA("America/Anguilla"),
    @XmlEnumValue("America/Antigua")
    AMERICA_ANTIGUA("America/Antigua"),
    @XmlEnumValue("America/Araguaina")
    AMERICA_ARAGUAINA("America/Araguaina"),
    @XmlEnumValue("America/Argentina/Buenos_Aires")
    AMERICA_ARGENTINA_BUENOS_AIRES("America/Argentina/Buenos_Aires"),
    @XmlEnumValue("America/Argentina/Catamarca")
    AMERICA_ARGENTINA_CATAMARCA("America/Argentina/Catamarca"),
    @XmlEnumValue("America/Argentina/Cordoba")
    AMERICA_ARGENTINA_CORDOBA("America/Argentina/Cordoba"),
    @XmlEnumValue("America/Argentina/Jujuy")
    AMERICA_ARGENTINA_JUJUY("America/Argentina/Jujuy"),
    @XmlEnumValue("America/Argentina/La_Rioja")
    AMERICA_ARGENTINA_LA_RIOJA("America/Argentina/La_Rioja"),
    @XmlEnumValue("America/Argentina/Mendoza")
    AMERICA_ARGENTINA_MENDOZA("America/Argentina/Mendoza"),
    @XmlEnumValue("America/Argentina/Rio_Gallegos")
    AMERICA_ARGENTINA_RIO_GALLEGOS("America/Argentina/Rio_Gallegos"),
    @XmlEnumValue("America/Argentina/Salta")
    AMERICA_ARGENTINA_SALTA("America/Argentina/Salta"),
    @XmlEnumValue("America/Argentina/San_Juan")
    AMERICA_ARGENTINA_SAN_JUAN("America/Argentina/San_Juan"),
    @XmlEnumValue("America/Argentina/San_Luis")
    AMERICA_ARGENTINA_SAN_LUIS("America/Argentina/San_Luis"),
    @XmlEnumValue("America/Argentina/Tucuman")
    AMERICA_ARGENTINA_TUCUMAN("America/Argentina/Tucuman"),
    @XmlEnumValue("America/Argentina/Ushuaia")
    AMERICA_ARGENTINA_USHUAIA("America/Argentina/Ushuaia"),
    @XmlEnumValue("America/Aruba")
    AMERICA_ARUBA("America/Aruba"),
    @XmlEnumValue("America/Asuncion")
    AMERICA_ASUNCION("America/Asuncion"),
    @XmlEnumValue("America/Atikokan")
    AMERICA_ATIKOKAN("America/Atikokan"),
    @XmlEnumValue("America/Bahia")
    AMERICA_BAHIA("America/Bahia"),
    @XmlEnumValue("America/Barbados")
    AMERICA_BARBADOS("America/Barbados"),
    @XmlEnumValue("America/Belem")
    AMERICA_BELEM("America/Belem"),
    @XmlEnumValue("America/Belize")
    AMERICA_BELIZE("America/Belize"),
    @XmlEnumValue("America/Blanc-Sablon")
    AMERICA_BLANC_SABLON("America/Blanc-Sablon"),
    @XmlEnumValue("America/Boa_Vista")
    AMERICA_BOA_VISTA("America/Boa_Vista"),
    @XmlEnumValue("America/Bogota")
    AMERICA_BOGOTA("America/Bogota"),
    @XmlEnumValue("America/Boise")
    AMERICA_BOISE("America/Boise"),
    @XmlEnumValue("America/Cambridge_Bay")
    AMERICA_CAMBRIDGE_BAY("America/Cambridge_Bay"),
    @XmlEnumValue("America/Campo_Grande")
    AMERICA_CAMPO_GRANDE("America/Campo_Grande"),
    @XmlEnumValue("America/Cancun")
    AMERICA_CANCUN("America/Cancun"),
    @XmlEnumValue("America/Caracas")
    AMERICA_CARACAS("America/Caracas"),
    @XmlEnumValue("America/Cayenne")
    AMERICA_CAYENNE("America/Cayenne"),
    @XmlEnumValue("America/Cayman")
    AMERICA_CAYMAN("America/Cayman"),
    @XmlEnumValue("America/Chicago")
    AMERICA_CHICAGO("America/Chicago"),
    @XmlEnumValue("America/Chihuahua")
    AMERICA_CHIHUAHUA("America/Chihuahua"),
    @XmlEnumValue("America/Costa_Rica")
    AMERICA_COSTA_RICA("America/Costa_Rica"),
    @XmlEnumValue("America/Cuiaba")
    AMERICA_CUIABA("America/Cuiaba"),
    @XmlEnumValue("America/Curacao")
    AMERICA_CURACAO("America/Curacao"),
    @XmlEnumValue("America/Danmarkshavn")
    AMERICA_DANMARKSHAVN("America/Danmarkshavn"),
    @XmlEnumValue("America/Dawson")
    AMERICA_DAWSON("America/Dawson"),
    @XmlEnumValue("America/Dawson_Creek")
    AMERICA_DAWSON_CREEK("America/Dawson_Creek"),
    @XmlEnumValue("America/Denver")
    AMERICA_DENVER("America/Denver"),
    @XmlEnumValue("America/Detroit")
    AMERICA_DETROIT("America/Detroit"),
    @XmlEnumValue("America/Dominica")
    AMERICA_DOMINICA("America/Dominica"),
    @XmlEnumValue("America/Edmonton")
    AMERICA_EDMONTON("America/Edmonton"),
    @XmlEnumValue("America/Eirunepe")
    AMERICA_EIRUNEPE("America/Eirunepe"),
    @XmlEnumValue("America/El_Salvador")
    AMERICA_EL_SALVADOR("America/El_Salvador"),
    @XmlEnumValue("America/Fortaleza")
    AMERICA_FORTALEZA("America/Fortaleza"),
    @XmlEnumValue("America/Glace_Bay")
    AMERICA_GLACE_BAY("America/Glace_Bay"),
    @XmlEnumValue("America/Godthab")
    AMERICA_GODTHAB("America/Godthab"),
    @XmlEnumValue("America/Goose_Bay")
    AMERICA_GOOSE_BAY("America/Goose_Bay"),
    @XmlEnumValue("America/Grand_Turk")
    AMERICA_GRAND_TURK("America/Grand_Turk"),
    @XmlEnumValue("America/Grenada")
    AMERICA_GRENADA("America/Grenada"),
    @XmlEnumValue("America/Guadeloupe")
    AMERICA_GUADELOUPE("America/Guadeloupe"),
    @XmlEnumValue("America/Guatemala")
    AMERICA_GUATEMALA("America/Guatemala"),
    @XmlEnumValue("America/Guayaquil")
    AMERICA_GUAYAQUIL("America/Guayaquil"),
    @XmlEnumValue("America/Guyana")
    AMERICA_GUYANA("America/Guyana"),
    @XmlEnumValue("America/Halifax")
    AMERICA_HALIFAX("America/Halifax"),
    @XmlEnumValue("America/Havana")
    AMERICA_HAVANA("America/Havana"),
    @XmlEnumValue("America/Hermosillo")
    AMERICA_HERMOSILLO("America/Hermosillo"),
    @XmlEnumValue("America/Indiana/Indianapolis")
    AMERICA_INDIANA_INDIANAPOLIS("America/Indiana/Indianapolis"),
    @XmlEnumValue("America/Indiana/Knox")
    AMERICA_INDIANA_KNOX("America/Indiana/Knox"),
    @XmlEnumValue("America/Indiana/Marengo")
    AMERICA_INDIANA_MARENGO("America/Indiana/Marengo"),
    @XmlEnumValue("America/Indiana/Petersburg")
    AMERICA_INDIANA_PETERSBURG("America/Indiana/Petersburg"),
    @XmlEnumValue("America/Indiana/Tell_City")
    AMERICA_INDIANA_TELL_CITY("America/Indiana/Tell_City"),
    @XmlEnumValue("America/Indiana/Vevay")
    AMERICA_INDIANA_VEVAY("America/Indiana/Vevay"),
    @XmlEnumValue("America/Indiana/Vincennes")
    AMERICA_INDIANA_VINCENNES("America/Indiana/Vincennes"),
    @XmlEnumValue("America/Indiana/Winamac")
    AMERICA_INDIANA_WINAMAC("America/Indiana/Winamac"),
    @XmlEnumValue("America/Inuvik")
    AMERICA_INUVIK("America/Inuvik"),
    @XmlEnumValue("America/Iqaluit")
    AMERICA_IQALUIT("America/Iqaluit"),
    @XmlEnumValue("America/Jamaica")
    AMERICA_JAMAICA("America/Jamaica"),
    @XmlEnumValue("America/Juneau")
    AMERICA_JUNEAU("America/Juneau"),
    @XmlEnumValue("America/Kentucky/Louisville")
    AMERICA_KENTUCKY_LOUISVILLE("America/Kentucky/Louisville"),
    @XmlEnumValue("America/Kentucky/Monticello")
    AMERICA_KENTUCKY_MONTICELLO("America/Kentucky/Monticello"),
    @XmlEnumValue("America/La_Paz")
    AMERICA_LA_PAZ("America/La_Paz"),
    @XmlEnumValue("America/Lima")
    AMERICA_LIMA("America/Lima"),
    @XmlEnumValue("America/Los_Angeles")
    AMERICA_LOS_ANGELES("America/Los_Angeles"),
    @XmlEnumValue("America/Maceio")
    AMERICA_MACEIO("America/Maceio"),
    @XmlEnumValue("America/Managua")
    AMERICA_MANAGUA("America/Managua"),
    @XmlEnumValue("America/Manaus")
    AMERICA_MANAUS("America/Manaus"),
    @XmlEnumValue("America/Marigot")
    AMERICA_MARIGOT("America/Marigot"),
    @XmlEnumValue("America/Martinique")
    AMERICA_MARTINIQUE("America/Martinique"),
    @XmlEnumValue("America/Mazatlan")
    AMERICA_MAZATLAN("America/Mazatlan"),
    @XmlEnumValue("America/Menominee")
    AMERICA_MENOMINEE("America/Menominee"),
    @XmlEnumValue("America/Merida")
    AMERICA_MERIDA("America/Merida"),
    @XmlEnumValue("America/Mexico_City")
    AMERICA_MEXICO_CITY("America/Mexico_City"),
    @XmlEnumValue("America/Miquelon")
    AMERICA_MIQUELON("America/Miquelon"),
    @XmlEnumValue("America/Moncton")
    AMERICA_MONCTON("America/Moncton"),
    @XmlEnumValue("America/Monterrey")
    AMERICA_MONTERREY("America/Monterrey"),
    @XmlEnumValue("America/Montevideo")
    AMERICA_MONTEVIDEO("America/Montevideo"),
    @XmlEnumValue("America/Montreal")
    AMERICA_MONTREAL("America/Montreal"),
    @XmlEnumValue("America/Montserrat")
    AMERICA_MONTSERRAT("America/Montserrat"),
    @XmlEnumValue("America/Nassau")
    AMERICA_NASSAU("America/Nassau"),
    @XmlEnumValue("America/New_York")
    AMERICA_NEW_YORK("America/New_York"),
    @XmlEnumValue("America/Nipigon")
    AMERICA_NIPIGON("America/Nipigon"),
    @XmlEnumValue("America/Nome")
    AMERICA_NOME("America/Nome"),
    @XmlEnumValue("America/Noronha")
    AMERICA_NORONHA("America/Noronha"),
    @XmlEnumValue("America/North_Dakota/Center")
    AMERICA_NORTH_DAKOTA_CENTER("America/North_Dakota/Center"),
    @XmlEnumValue("America/North_Dakota/New_Salem")
    AMERICA_NORTH_DAKOTA_NEW_SALEM("America/North_Dakota/New_Salem"),
    @XmlEnumValue("America/Panama")
    AMERICA_PANAMA("America/Panama"),
    @XmlEnumValue("America/Pangnirtung")
    AMERICA_PANGNIRTUNG("America/Pangnirtung"),
    @XmlEnumValue("America/Paramaribo")
    AMERICA_PARAMARIBO("America/Paramaribo"),
    @XmlEnumValue("America/Phoenix")
    AMERICA_PHOENIX("America/Phoenix"),
    @XmlEnumValue("America/Port-au-Prince")
    AMERICA_PORT_AU_PRINCE("America/Port-au-Prince"),
    @XmlEnumValue("America/Port_of_Spain")
    AMERICA_PORT_OF_SPAIN("America/Port_of_Spain"),
    @XmlEnumValue("America/Porto_Velho")
    AMERICA_PORTO_VELHO("America/Porto_Velho"),
    @XmlEnumValue("America/Puerto_Rico")
    AMERICA_PUERTO_RICO("America/Puerto_Rico"),
    @XmlEnumValue("America/Rainy_River")
    AMERICA_RAINY_RIVER("America/Rainy_River"),
    @XmlEnumValue("America/Rankin_Inlet")
    AMERICA_RANKIN_INLET("America/Rankin_Inlet"),
    @XmlEnumValue("America/Recife")
    AMERICA_RECIFE("America/Recife"),
    @XmlEnumValue("America/Regina")
    AMERICA_REGINA("America/Regina"),
    @XmlEnumValue("America/Resolute")
    AMERICA_RESOLUTE("America/Resolute"),
    @XmlEnumValue("America/Rio_Branco")
    AMERICA_RIO_BRANCO("America/Rio_Branco"),
    @XmlEnumValue("America/Santarem")
    AMERICA_SANTAREM("America/Santarem"),
    @XmlEnumValue("America/Santiago")
    AMERICA_SANTIAGO("America/Santiago"),
    @XmlEnumValue("America/Santo_Domingo")
    AMERICA_SANTO_DOMINGO("America/Santo_Domingo"),
    @XmlEnumValue("America/Sao_Paulo")
    AMERICA_SAO_PAULO("America/Sao_Paulo"),
    @XmlEnumValue("America/Scoresbysund")
    AMERICA_SCORESBYSUND("America/Scoresbysund"),
    @XmlEnumValue("America/Shiprock")
    AMERICA_SHIPROCK("America/Shiprock"),
    @XmlEnumValue("America/St_Barthelemy")
    AMERICA_ST_BARTHELEMY("America/St_Barthelemy"),
    @XmlEnumValue("America/St_Johns")
    AMERICA_ST_JOHNS("America/St_Johns"),
    @XmlEnumValue("America/St_Kitts")
    AMERICA_ST_KITTS("America/St_Kitts"),
    @XmlEnumValue("America/St_Lucia")
    AMERICA_ST_LUCIA("America/St_Lucia"),
    @XmlEnumValue("America/St_Thomas")
    AMERICA_ST_THOMAS("America/St_Thomas"),
    @XmlEnumValue("America/St_Vincent")
    AMERICA_ST_VINCENT("America/St_Vincent"),
    @XmlEnumValue("America/Swift_Current")
    AMERICA_SWIFT_CURRENT("America/Swift_Current"),
    @XmlEnumValue("America/Tegucigalpa")
    AMERICA_TEGUCIGALPA("America/Tegucigalpa"),
    @XmlEnumValue("America/Thule")
    AMERICA_THULE("America/Thule"),
    @XmlEnumValue("America/Thunder_Bay")
    AMERICA_THUNDER_BAY("America/Thunder_Bay"),
    @XmlEnumValue("America/Tijuana")
    AMERICA_TIJUANA("America/Tijuana"),
    @XmlEnumValue("America/Toronto")
    AMERICA_TORONTO("America/Toronto"),
    @XmlEnumValue("America/Tortola")
    AMERICA_TORTOLA("America/Tortola"),
    @XmlEnumValue("America/Vancouver")
    AMERICA_VANCOUVER("America/Vancouver"),
    @XmlEnumValue("America/Whitehorse")
    AMERICA_WHITEHORSE("America/Whitehorse"),
    @XmlEnumValue("America/Winnipeg")
    AMERICA_WINNIPEG("America/Winnipeg"),
    @XmlEnumValue("America/Yakutat")
    AMERICA_YAKUTAT("America/Yakutat"),
    @XmlEnumValue("America/Yellowknife")
    AMERICA_YELLOWKNIFE("America/Yellowknife"),
    @XmlEnumValue("Antarctica/Casey")
    ANTARCTICA_CASEY("Antarctica/Casey"),
    @XmlEnumValue("Antarctica/Davis")
    ANTARCTICA_DAVIS("Antarctica/Davis"),
    @XmlEnumValue("Antarctica/DumontDUrville")
    ANTARCTICA_DUMONT_D_URVILLE("Antarctica/DumontDUrville"),
    @XmlEnumValue("Antarctica/Mawson")
    ANTARCTICA_MAWSON("Antarctica/Mawson"),
    @XmlEnumValue("Antarctica/McMurdo")
    ANTARCTICA_MC_MURDO("Antarctica/McMurdo"),
    @XmlEnumValue("Antarctica/Palmer")
    ANTARCTICA_PALMER("Antarctica/Palmer"),
    @XmlEnumValue("Antarctica/Rothera")
    ANTARCTICA_ROTHERA("Antarctica/Rothera"),
    @XmlEnumValue("Antarctica/South_Pole")
    ANTARCTICA_SOUTH_POLE("Antarctica/South_Pole"),
    @XmlEnumValue("Antarctica/Syowa")
    ANTARCTICA_SYOWA("Antarctica/Syowa"),
    @XmlEnumValue("Antarctica/Vostok")
    ANTARCTICA_VOSTOK("Antarctica/Vostok"),
    @XmlEnumValue("Arctic/Longyearbyen")
    ARCTIC_LONGYEARBYEN("Arctic/Longyearbyen"),
    @XmlEnumValue("Asia/Aden")
    ASIA_ADEN("Asia/Aden"),
    @XmlEnumValue("Asia/Almaty")
    ASIA_ALMATY("Asia/Almaty"),
    @XmlEnumValue("Asia/Amman")
    ASIA_AMMAN("Asia/Amman"),
    @XmlEnumValue("Asia/Anadyr")
    ASIA_ANADYR("Asia/Anadyr"),
    @XmlEnumValue("Asia/Aqtau")
    ASIA_AQTAU("Asia/Aqtau"),
    @XmlEnumValue("Asia/Aqtobe")
    ASIA_AQTOBE("Asia/Aqtobe"),
    @XmlEnumValue("Asia/Ashgabat")
    ASIA_ASHGABAT("Asia/Ashgabat"),
    @XmlEnumValue("Asia/Baghdad")
    ASIA_BAGHDAD("Asia/Baghdad"),
    @XmlEnumValue("Asia/Bahrain")
    ASIA_BAHRAIN("Asia/Bahrain"),
    @XmlEnumValue("Asia/Baku")
    ASIA_BAKU("Asia/Baku"),
    @XmlEnumValue("Asia/Bangkok")
    ASIA_BANGKOK("Asia/Bangkok"),
    @XmlEnumValue("Asia/Beirut")
    ASIA_BEIRUT("Asia/Beirut"),
    @XmlEnumValue("Asia/Bishkek")
    ASIA_BISHKEK("Asia/Bishkek"),
    @XmlEnumValue("Asia/Brunei")
    ASIA_BRUNEI("Asia/Brunei"),
    @XmlEnumValue("Asia/Choibalsan")
    ASIA_CHOIBALSAN("Asia/Choibalsan"),
    @XmlEnumValue("Asia/Chongqing")
    ASIA_CHONGQING("Asia/Chongqing"),
    @XmlEnumValue("Asia/Colombo")
    ASIA_COLOMBO("Asia/Colombo"),
    @XmlEnumValue("Asia/Damascus")
    ASIA_DAMASCUS("Asia/Damascus"),
    @XmlEnumValue("Asia/Dhaka")
    ASIA_DHAKA("Asia/Dhaka"),
    @XmlEnumValue("Asia/Dili")
    ASIA_DILI("Asia/Dili"),
    @XmlEnumValue("Asia/Dubai")
    ASIA_DUBAI("Asia/Dubai"),
    @XmlEnumValue("Asia/Dushanbe")
    ASIA_DUSHANBE("Asia/Dushanbe"),
    @XmlEnumValue("Asia/Gaza")
    ASIA_GAZA("Asia/Gaza"),
    @XmlEnumValue("Asia/Harbin")
    ASIA_HARBIN("Asia/Harbin"),
    @XmlEnumValue("Asia/Ho_Chi_Minh")
    ASIA_HO_CHI_MINH("Asia/Ho_Chi_Minh"),
    @XmlEnumValue("Asia/Hong_Kong")
    ASIA_HONG_KONG("Asia/Hong_Kong"),
    @XmlEnumValue("Asia/Hovd")
    ASIA_HOVD("Asia/Hovd"),
    @XmlEnumValue("Asia/Irkutsk")
    ASIA_IRKUTSK("Asia/Irkutsk"),
    @XmlEnumValue("Asia/Jakarta")
    ASIA_JAKARTA("Asia/Jakarta"),
    @XmlEnumValue("Asia/Jayapura")
    ASIA_JAYAPURA("Asia/Jayapura"),
    @XmlEnumValue("Asia/Jerusalem")
    ASIA_JERUSALEM("Asia/Jerusalem"),
    @XmlEnumValue("Asia/Kabul")
    ASIA_KABUL("Asia/Kabul"),
    @XmlEnumValue("Asia/Kamchatka")
    ASIA_KAMCHATKA("Asia/Kamchatka"),
    @XmlEnumValue("Asia/Karachi")
    ASIA_KARACHI("Asia/Karachi"),
    @XmlEnumValue("Asia/Kashgar")
    ASIA_KASHGAR("Asia/Kashgar"),
    @XmlEnumValue("Asia/Katmandu")
    ASIA_KATMANDU("Asia/Katmandu"),
    @XmlEnumValue("Asia/Kolkata")
    ASIA_KOLKATA("Asia/Kolkata"),
    @XmlEnumValue("Asia/Krasnoyarsk")
    ASIA_KRASNOYARSK("Asia/Krasnoyarsk"),
    @XmlEnumValue("Asia/Kuala_Lumpur")
    ASIA_KUALA_LUMPUR("Asia/Kuala_Lumpur"),
    @XmlEnumValue("Asia/Kuching")
    ASIA_KUCHING("Asia/Kuching"),
    @XmlEnumValue("Asia/Kuwait")
    ASIA_KUWAIT("Asia/Kuwait"),
    @XmlEnumValue("Asia/Macau")
    ASIA_MACAU("Asia/Macau"),
    @XmlEnumValue("Asia/Magadan")
    ASIA_MAGADAN("Asia/Magadan"),
    @XmlEnumValue("Asia/Makassar")
    ASIA_MAKASSAR("Asia/Makassar"),
    @XmlEnumValue("Asia/Manila")
    ASIA_MANILA("Asia/Manila"),
    @XmlEnumValue("Asia/Muscat")
    ASIA_MUSCAT("Asia/Muscat"),
    @XmlEnumValue("Asia/Nicosia")
    ASIA_NICOSIA("Asia/Nicosia"),
    @XmlEnumValue("Asia/Novosibirsk")
    ASIA_NOVOSIBIRSK("Asia/Novosibirsk"),
    @XmlEnumValue("Asia/Omsk")
    ASIA_OMSK("Asia/Omsk"),
    @XmlEnumValue("Asia/Oral")
    ASIA_ORAL("Asia/Oral"),
    @XmlEnumValue("Asia/Phnom_Penh")
    ASIA_PHNOM_PENH("Asia/Phnom_Penh"),
    @XmlEnumValue("Asia/Pontianak")
    ASIA_PONTIANAK("Asia/Pontianak"),
    @XmlEnumValue("Asia/Pyongyang")
    ASIA_PYONGYANG("Asia/Pyongyang"),
    @XmlEnumValue("Asia/Qatar")
    ASIA_QATAR("Asia/Qatar"),
    @XmlEnumValue("Asia/Qyzylorda")
    ASIA_QYZYLORDA("Asia/Qyzylorda"),
    @XmlEnumValue("Asia/Rangoon")
    ASIA_RANGOON("Asia/Rangoon"),
    @XmlEnumValue("Asia/Riyadh")
    ASIA_RIYADH("Asia/Riyadh"),
    @XmlEnumValue("Asia/Sakhalin")
    ASIA_SAKHALIN("Asia/Sakhalin"),
    @XmlEnumValue("Asia/Samarkand")
    ASIA_SAMARKAND("Asia/Samarkand"),
    @XmlEnumValue("Asia/Seoul")
    ASIA_SEOUL("Asia/Seoul"),
    @XmlEnumValue("Asia/Shanghai")
    ASIA_SHANGHAI("Asia/Shanghai"),
    @XmlEnumValue("Asia/Singapore")
    ASIA_SINGAPORE("Asia/Singapore"),
    @XmlEnumValue("Asia/Taipei")
    ASIA_TAIPEI("Asia/Taipei"),
    @XmlEnumValue("Asia/Tashkent")
    ASIA_TASHKENT("Asia/Tashkent"),
    @XmlEnumValue("Asia/Tbilisi")
    ASIA_TBILISI("Asia/Tbilisi"),
    @XmlEnumValue("Asia/Tehran")
    ASIA_TEHRAN("Asia/Tehran"),
    @XmlEnumValue("Asia/Thimphu")
    ASIA_THIMPHU("Asia/Thimphu"),
    @XmlEnumValue("Asia/Tokyo")
    ASIA_TOKYO("Asia/Tokyo"),
    @XmlEnumValue("Asia/Ulaanbaatar")
    ASIA_ULAANBAATAR("Asia/Ulaanbaatar"),
    @XmlEnumValue("Asia/Urumqi")
    ASIA_URUMQI("Asia/Urumqi"),
    @XmlEnumValue("Asia/Vientiane")
    ASIA_VIENTIANE("Asia/Vientiane"),
    @XmlEnumValue("Asia/Vladivostok")
    ASIA_VLADIVOSTOK("Asia/Vladivostok"),
    @XmlEnumValue("Asia/Yakutsk")
    ASIA_YAKUTSK("Asia/Yakutsk"),
    @XmlEnumValue("Asia/Yekaterinburg")
    ASIA_YEKATERINBURG("Asia/Yekaterinburg"),
    @XmlEnumValue("Asia/Yerevan")
    ASIA_YEREVAN("Asia/Yerevan"),
    @XmlEnumValue("Atlantic/Azores")
    ATLANTIC_AZORES("Atlantic/Azores"),
    @XmlEnumValue("Atlantic/Bermuda")
    ATLANTIC_BERMUDA("Atlantic/Bermuda"),
    @XmlEnumValue("Atlantic/Canary")
    ATLANTIC_CANARY("Atlantic/Canary"),
    @XmlEnumValue("Atlantic/Cape_Verde")
    ATLANTIC_CAPE_VERDE("Atlantic/Cape_Verde"),
    @XmlEnumValue("Atlantic/Faroe")
    ATLANTIC_FAROE("Atlantic/Faroe"),
    @XmlEnumValue("Atlantic/Madeira")
    ATLANTIC_MADEIRA("Atlantic/Madeira"),
    @XmlEnumValue("Atlantic/Reykjavik")
    ATLANTIC_REYKJAVIK("Atlantic/Reykjavik"),
    @XmlEnumValue("Atlantic/South_Georgia")
    ATLANTIC_SOUTH_GEORGIA("Atlantic/South_Georgia"),
    @XmlEnumValue("Atlantic/St_Helena")
    ATLANTIC_ST_HELENA("Atlantic/St_Helena"),
    @XmlEnumValue("Atlantic/Stanley")
    ATLANTIC_STANLEY("Atlantic/Stanley"),
    @XmlEnumValue("Australia/Adelaide")
    AUSTRALIA_ADELAIDE("Australia/Adelaide"),
    @XmlEnumValue("Australia/Brisbane")
    AUSTRALIA_BRISBANE("Australia/Brisbane"),
    @XmlEnumValue("Australia/Broken_Hill")
    AUSTRALIA_BROKEN_HILL("Australia/Broken_Hill"),
    @XmlEnumValue("Australia/Currie")
    AUSTRALIA_CURRIE("Australia/Currie"),
    @XmlEnumValue("Australia/Darwin")
    AUSTRALIA_DARWIN("Australia/Darwin"),
    @XmlEnumValue("Australia/Eucla")
    AUSTRALIA_EUCLA("Australia/Eucla"),
    @XmlEnumValue("Australia/Hobart")
    AUSTRALIA_HOBART("Australia/Hobart"),
    @XmlEnumValue("Australia/Lindeman")
    AUSTRALIA_LINDEMAN("Australia/Lindeman"),
    @XmlEnumValue("Australia/Lord_Howe")
    AUSTRALIA_LORD_HOWE("Australia/Lord_Howe"),
    @XmlEnumValue("Australia/Melbourne")
    AUSTRALIA_MELBOURNE("Australia/Melbourne"),
    @XmlEnumValue("Australia/Perth")
    AUSTRALIA_PERTH("Australia/Perth"),
    @XmlEnumValue("Australia/Sydney")
    AUSTRALIA_SYDNEY("Australia/Sydney"),
    @XmlEnumValue("Europe/Amsterdam")
    EUROPE_AMSTERDAM("Europe/Amsterdam"),
    @XmlEnumValue("Europe/Andorra")
    EUROPE_ANDORRA("Europe/Andorra"),
    @XmlEnumValue("Europe/Athens")
    EUROPE_ATHENS("Europe/Athens"),
    @XmlEnumValue("Europe/Belgrade")
    EUROPE_BELGRADE("Europe/Belgrade"),
    @XmlEnumValue("Europe/Berlin")
    EUROPE_BERLIN("Europe/Berlin"),
    @XmlEnumValue("Europe/Bratislava")
    EUROPE_BRATISLAVA("Europe/Bratislava"),
    @XmlEnumValue("Europe/Brussels")
    EUROPE_BRUSSELS("Europe/Brussels"),
    @XmlEnumValue("Europe/Bucharest")
    EUROPE_BUCHAREST("Europe/Bucharest"),
    @XmlEnumValue("Europe/Budapest")
    EUROPE_BUDAPEST("Europe/Budapest"),
    @XmlEnumValue("Europe/Chisinau")
    EUROPE_CHISINAU("Europe/Chisinau"),
    @XmlEnumValue("Europe/Copenhagen")
    EUROPE_COPENHAGEN("Europe/Copenhagen"),
    @XmlEnumValue("Europe/Dublin")
    EUROPE_DUBLIN("Europe/Dublin"),
    @XmlEnumValue("Europe/Gibraltar")
    EUROPE_GIBRALTAR("Europe/Gibraltar"),
    @XmlEnumValue("Europe/Guernsey")
    EUROPE_GUERNSEY("Europe/Guernsey"),
    @XmlEnumValue("Europe/Helsinki")
    EUROPE_HELSINKI("Europe/Helsinki"),
    @XmlEnumValue("Europe/Isle_of_Man")
    EUROPE_ISLE_OF_MAN("Europe/Isle_of_Man"),
    @XmlEnumValue("Europe/Istanbul")
    EUROPE_ISTANBUL("Europe/Istanbul"),
    @XmlEnumValue("Europe/Jersey")
    EUROPE_JERSEY("Europe/Jersey"),
    @XmlEnumValue("Europe/Kaliningrad")
    EUROPE_KALININGRAD("Europe/Kaliningrad"),
    @XmlEnumValue("Europe/Kiev")
    EUROPE_KIEV("Europe/Kiev"),
    @XmlEnumValue("Europe/Lisbon")
    EUROPE_LISBON("Europe/Lisbon"),
    @XmlEnumValue("Europe/Ljubljana")
    EUROPE_LJUBLJANA("Europe/Ljubljana"),
    @XmlEnumValue("Europe/London")
    EUROPE_LONDON("Europe/London"),
    @XmlEnumValue("Europe/Luxembourg")
    EUROPE_LUXEMBOURG("Europe/Luxembourg"),
    @XmlEnumValue("Europe/Madrid")
    EUROPE_MADRID("Europe/Madrid"),
    @XmlEnumValue("Europe/Malta")
    EUROPE_MALTA("Europe/Malta"),
    @XmlEnumValue("Europe/Mariehamn")
    EUROPE_MARIEHAMN("Europe/Mariehamn"),
    @XmlEnumValue("Europe/Minsk")
    EUROPE_MINSK("Europe/Minsk"),
    @XmlEnumValue("Europe/Monaco")
    EUROPE_MONACO("Europe/Monaco"),
    @XmlEnumValue("Europe/Moscow")
    EUROPE_MOSCOW("Europe/Moscow"),
    @XmlEnumValue("Europe/Oslo")
    EUROPE_OSLO("Europe/Oslo"),
    @XmlEnumValue("Europe/Paris")
    EUROPE_PARIS("Europe/Paris"),
    @XmlEnumValue("Europe/Podgorica")
    EUROPE_PODGORICA("Europe/Podgorica"),
    @XmlEnumValue("Europe/Prague")
    EUROPE_PRAGUE("Europe/Prague"),
    @XmlEnumValue("Europe/Riga")
    EUROPE_RIGA("Europe/Riga"),
    @XmlEnumValue("Europe/Rome")
    EUROPE_ROME("Europe/Rome"),
    @XmlEnumValue("Europe/Samara")
    EUROPE_SAMARA("Europe/Samara"),
    @XmlEnumValue("Europe/San_Marino")
    EUROPE_SAN_MARINO("Europe/San_Marino"),
    @XmlEnumValue("Europe/Sarajevo")
    EUROPE_SARAJEVO("Europe/Sarajevo"),
    @XmlEnumValue("Europe/Simferopol")
    EUROPE_SIMFEROPOL("Europe/Simferopol"),
    @XmlEnumValue("Europe/Skopje")
    EUROPE_SKOPJE("Europe/Skopje"),
    @XmlEnumValue("Europe/Sofia")
    EUROPE_SOFIA("Europe/Sofia"),
    @XmlEnumValue("Europe/Stockholm")
    EUROPE_STOCKHOLM("Europe/Stockholm"),
    @XmlEnumValue("Europe/Tallinn")
    EUROPE_TALLINN("Europe/Tallinn"),
    @XmlEnumValue("Europe/Tirane")
    EUROPE_TIRANE("Europe/Tirane"),
    @XmlEnumValue("Europe/Uzhgorod")
    EUROPE_UZHGOROD("Europe/Uzhgorod"),
    @XmlEnumValue("Europe/Vaduz")
    EUROPE_VADUZ("Europe/Vaduz"),
    @XmlEnumValue("Europe/Vatican")
    EUROPE_VATICAN("Europe/Vatican"),
    @XmlEnumValue("Europe/Vienna")
    EUROPE_VIENNA("Europe/Vienna"),
    @XmlEnumValue("Europe/Vilnius")
    EUROPE_VILNIUS("Europe/Vilnius"),
    @XmlEnumValue("Europe/Volgograd")
    EUROPE_VOLGOGRAD("Europe/Volgograd"),
    @XmlEnumValue("Europe/Warsaw")
    EUROPE_WARSAW("Europe/Warsaw"),
    @XmlEnumValue("Europe/Zagreb")
    EUROPE_ZAGREB("Europe/Zagreb"),
    @XmlEnumValue("Europe/Zaporozhye")
    EUROPE_ZAPOROZHYE("Europe/Zaporozhye"),
    @XmlEnumValue("Europe/Zurich")
    EUROPE_ZURICH("Europe/Zurich"),
    @XmlEnumValue("Indian/Antananarivo")
    INDIAN_ANTANANARIVO("Indian/Antananarivo"),
    @XmlEnumValue("Indian/Chagos")
    INDIAN_CHAGOS("Indian/Chagos"),
    @XmlEnumValue("Indian/Christmas")
    INDIAN_CHRISTMAS("Indian/Christmas"),
    @XmlEnumValue("Indian/Cocos")
    INDIAN_COCOS("Indian/Cocos"),
    @XmlEnumValue("Indian/Comoro")
    INDIAN_COMORO("Indian/Comoro"),
    @XmlEnumValue("Indian/Kerguelen")
    INDIAN_KERGUELEN("Indian/Kerguelen"),
    @XmlEnumValue("Indian/Mahe")
    INDIAN_MAHE("Indian/Mahe"),
    @XmlEnumValue("Indian/Maldives")
    INDIAN_MALDIVES("Indian/Maldives"),
    @XmlEnumValue("Indian/Mauritius")
    INDIAN_MAURITIUS("Indian/Mauritius"),
    @XmlEnumValue("Indian/Mayotte")
    INDIAN_MAYOTTE("Indian/Mayotte"),
    @XmlEnumValue("Indian/Reunion")
    INDIAN_REUNION("Indian/Reunion"),
    @XmlEnumValue("Pacific/Apia")
    PACIFIC_APIA("Pacific/Apia"),
    @XmlEnumValue("Pacific/Auckland")
    PACIFIC_AUCKLAND("Pacific/Auckland"),
    @XmlEnumValue("Pacific/Chatham")
    PACIFIC_CHATHAM("Pacific/Chatham"),
    @XmlEnumValue("Pacific/Easter")
    PACIFIC_EASTER("Pacific/Easter"),
    @XmlEnumValue("Pacific/Efate")
    PACIFIC_EFATE("Pacific/Efate"),
    @XmlEnumValue("Pacific/Enderbury")
    PACIFIC_ENDERBURY("Pacific/Enderbury"),
    @XmlEnumValue("Pacific/Fakaofo")
    PACIFIC_FAKAOFO("Pacific/Fakaofo"),
    @XmlEnumValue("Pacific/Fiji")
    PACIFIC_FIJI("Pacific/Fiji"),
    @XmlEnumValue("Pacific/Funafuti")
    PACIFIC_FUNAFUTI("Pacific/Funafuti"),
    @XmlEnumValue("Pacific/Galapagos")
    PACIFIC_GALAPAGOS("Pacific/Galapagos"),
    @XmlEnumValue("Pacific/Gambier")
    PACIFIC_GAMBIER("Pacific/Gambier"),
    @XmlEnumValue("Pacific/Guadalcanal")
    PACIFIC_GUADALCANAL("Pacific/Guadalcanal"),
    @XmlEnumValue("Pacific/Guam")
    PACIFIC_GUAM("Pacific/Guam"),
    @XmlEnumValue("Pacific/Honolulu")
    PACIFIC_HONOLULU("Pacific/Honolulu"),
    @XmlEnumValue("Pacific/Johnston")
    PACIFIC_JOHNSTON("Pacific/Johnston"),
    @XmlEnumValue("Pacific/Kiritimati")
    PACIFIC_KIRITIMATI("Pacific/Kiritimati"),
    @XmlEnumValue("Pacific/Kosrae")
    PACIFIC_KOSRAE("Pacific/Kosrae"),
    @XmlEnumValue("Pacific/Kwajalein")
    PACIFIC_KWAJALEIN("Pacific/Kwajalein"),
    @XmlEnumValue("Pacific/Majuro")
    PACIFIC_MAJURO("Pacific/Majuro"),
    @XmlEnumValue("Pacific/Marquesas")
    PACIFIC_MARQUESAS("Pacific/Marquesas"),
    @XmlEnumValue("Pacific/Midway")
    PACIFIC_MIDWAY("Pacific/Midway"),
    @XmlEnumValue("Pacific/Nauru")
    PACIFIC_NAURU("Pacific/Nauru"),
    @XmlEnumValue("Pacific/Niue")
    PACIFIC_NIUE("Pacific/Niue"),
    @XmlEnumValue("Pacific/Norfolk")
    PACIFIC_NORFOLK("Pacific/Norfolk"),
    @XmlEnumValue("Pacific/Noumea")
    PACIFIC_NOUMEA("Pacific/Noumea"),
    @XmlEnumValue("Pacific/Pago_Pago")
    PACIFIC_PAGO_PAGO("Pacific/Pago_Pago"),
    @XmlEnumValue("Pacific/Palau")
    PACIFIC_PALAU("Pacific/Palau"),
    @XmlEnumValue("Pacific/Pitcairn")
    PACIFIC_PITCAIRN("Pacific/Pitcairn"),
    @XmlEnumValue("Pacific/Ponape")
    PACIFIC_PONAPE("Pacific/Ponape"),
    @XmlEnumValue("Pacific/Port_Moresby")
    PACIFIC_PORT_MORESBY("Pacific/Port_Moresby"),
    @XmlEnumValue("Pacific/Rarotonga")
    PACIFIC_RAROTONGA("Pacific/Rarotonga"),
    @XmlEnumValue("Pacific/Saipan")
    PACIFIC_SAIPAN("Pacific/Saipan"),
    @XmlEnumValue("Pacific/Tahiti")
    PACIFIC_TAHITI("Pacific/Tahiti"),
    @XmlEnumValue("Pacific/Tarawa")
    PACIFIC_TARAWA("Pacific/Tarawa"),
    @XmlEnumValue("Pacific/Tongatapu")
    PACIFIC_TONGATAPU("Pacific/Tongatapu"),
    @XmlEnumValue("Pacific/Truk")
    PACIFIC_TRUK("Pacific/Truk"),
    @XmlEnumValue("Pacific/Wake")
    PACIFIC_WAKE("Pacific/Wake"),
    @XmlEnumValue("Pacific/Wallis")
    PACIFIC_WALLIS("Pacific/Wallis");
    private final String value;

    Timezone(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static Timezone fromValue(String v) {
        for (Timezone c: Timezone.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
