//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 10:55:05 AM CST 
//


package org.atdl4j.fixatdl.flow;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.atdl4j.fixatdl.flow package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private static final QName _StateRule_QNAME = new QName("http://www.fixprotocol.org/FIXatdl-1-1/Flow", "StateRule");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.atdl4j.fixatdl.flow
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link StateRuleT }
     * 
     */
    public StateRuleT createStateRuleT() {
        return new StateRuleT();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StateRuleT }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.fixprotocol.org/FIXatdl-1-1/Flow", name = "StateRule")
    public JAXBElement<StateRuleT> createStateRule(StateRuleT value) {
        return new JAXBElement<>(_StateRule_QNAME, StateRuleT.class, null, value);
    }

}
