//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.02.24 at 10:55:05 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.fixprotocol.org/FIXatdl-1-1/Flow", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.atdl4j.fixatdl.flow;
